mimosa: mimosa::stream::DirectFdStream Class Reference
mimosa::stream::DirectFdStream Class Reference
#include <direct-fd-stream.hh>
Public Member Functions
MIMOSA_DEF_PTR (DirectFdStream)
DirectFdStream (int fd, bool is_readable=1, bool is_writable=1, bool is_regular_file=false)
virtual ~DirectFdStream ()
virtual int64_t write (const char *data, uint64_t nbytes, runtime::Time timeout=0)
virtual int64_t writev (const struct iovec *iov, int iovcnt, runtime::Time timeout=0)
virtual int64_t read (char *data, uint64_t nbytes, runtime::Time timeout=0)
virtual int64_t readv (const struct iovec *iov, int iovcnt, runtime::Time timeout=0)
int fd () const
Static Public Member Functions
static DirectFdStream::Ptr openFile (const char *path, int oflags=O_RDONLY, mode_t mode=0644)
Detailed Description
Definition at line 14 of file direct-fd-stream.hh.
Constructor & Destructor Documentation
mimosa::stream::DirectFdStream::DirectFdStream (int fd, bool is_readable = 1, bool is_writable = 1, bool is_regular_file = false)
Definition at line 9 of file direct-fd-stream.cc.
Referenced by openFile().
      : fd_(fd),
        is_readable_(is_readable),
        is_writable_(is_writable),
        is_regular_file_(is_regular_file)
    {
    }
mimosa::stream::DirectFdStream::~DirectFdStream () [virtual]
Definition at line 17 of file direct-fd-stream.cc.
    {
      ::melon_close(fd_);
      fd_ = -1;
    }
Member Function Documentation
int mimosa::stream::DirectFdStream::fd () const [inline]
Definition at line 29 of file direct-fd-stream.hh.
Referenced by openFile().
{ return fd_; }
mimosa::stream::DirectFdStream::MIMOSA_DEF_PTR (DirectFdStream)
DirectFdStream::Ptr mimosa::stream::DirectFdStream::openFile (const char * path, int oflags = O_RDONLY, mode_t mode = 0644) [static]
Definition at line 72 of file direct-fd-stream.cc.
References DirectFdStream(), and fd().
    {
      int fd = ::open(path, oflags, mode);
      if (fd < 0)
        return nullptr;
      return new DirectFdStream(fd,
                                (oflags & O_RDWR) || !(oflags & O_WRONLY),
                                (oflags & O_RDWR) || (oflags & O_WRONLY),
                                true);
    }
int64_t mimosa::stream::DirectFdStream::read (char * data, uint64_t nbytes, runtime::Time timeout = 0) [virtual]
Implements mimosa::stream::Stream.
Definition at line 48 of file direct-fd-stream.cc.
    {
      if (!is_readable_)
      {
        errno = EINVAL;
        return -1;
      }
      return is_regular_file_ ? ::read(fd_, data, nbytes)
        : ::melon_read(fd_, data, nbytes, timeout);
    }
int64_t mimosa::stream::DirectFdStream::readv (const struct iovec * iov, int iovcnt, runtime::Time timeout = 0) [virtual]
Reimplemented from mimosa::stream::Stream.
Definition at line 60 of file direct-fd-stream.cc.
    {
      if (!is_readable_)
      {
        errno = EINVAL;
        return -1;
      }
      return is_regular_file_ ? ::readv(fd_, iov, iovcnt < IOV_MAX ? iovcnt : IOV_MAX)
        : ::melon_readv(fd_, iov, iovcnt < IOV_MAX ? iovcnt : IOV_MAX, timeout);
    }
int64_t mimosa::stream::DirectFdStream::write (const char * data, uint64_t nbytes, runtime::Time timeout = 0) [virtual]
Implements mimosa::stream::Stream.
Definition at line 24 of file direct-fd-stream.cc.
    {
      if (!is_writable_)
      {
        errno = EINVAL;
        return -1;
      }
      return is_regular_file_ ? ::write(fd_, data, nbytes)
        : ::melon_write(fd_, data, nbytes, timeout);
    }
int64_t mimosa::stream::DirectFdStream::writev (const struct iovec * iov, int iovcnt, runtime::Time timeout = 0) [virtual]
Reimplemented from mimosa::stream::Stream.
Definition at line 36 of file direct-fd-stream.cc.
    {
      if (!is_writable_)
      {
        errno = EINVAL;
        return -1;
      }
      return is_regular_file_ ? ::writev(fd_, iov, iovcnt < IOV_MAX ? iovcnt : IOV_MAX)
        : ::melon_writev(fd_, iov, iovcnt < IOV_MAX ? iovcnt : IOV_MAX, timeout);
    }
The documentation for this class was generated from the following files:
mimosa/stream/direct-fd-stream.hh
mimosa/stream/direct-fd-stream.cc