mimosa: mimosa::http::RequestReader Class Reference
mimosa::http::RequestReader Class Reference
#include <request-reader.hh>
Public Member Functions
MIMOSA_DEF_PTR (RequestReader)
RequestReader (stream::Stream::Ptr stream)
void clear ()
container::kvs & form ()
virtual int64_t write (const char *data, uint64_t nbytes, runtime::Time timeout=0)
virtual int64_t read (char *data, uint64_t nbytes, runtime::Time timeout=0)
virtual bool flush (runtime::Time timeout=0)
Friends
class ServerChannel
Detailed Description
Definition at line 11 of file request-reader.hh.
Constructor & Destructor Documentation
mimosa::http::RequestReader::RequestReader (stream::Stream::Ptr stream)
Definition at line 12 of file request-reader.cc.
      : stream_(stream),
        bytes_left_(0),
        parsed_form_(false),
        form_()
    {
    }
Member Function Documentation
void mimosa::http::RequestReader::clear ()
Reimplemented from mimosa::http::Request.
Definition at line 21 of file request-reader.cc.
    {
      bytes_left_ = 0;
      parsed_form_ = false;
      form_.clear();
    }
bool mimosa::http::RequestReader::flush (runtime::Time timeout = 0) [virtual]
reads and discards all remaining body data
Reimplemented from mimosa::stream::Stream.
Definition at line 55 of file request-reader.cc.
References mimosa::stream::Buffer::data(), read(), and mimosa::stream::Buffer::size().
    {
      stream::Buffer buffer;
      while (bytes_left_ > 0)
        if (read(buffer.data(), buffer.size(), timeout) <= 0)
          return false;
      return true;
    }
container::kvs & mimosa::http::RequestReader::form ()
Definition at line 65 of file request-reader.cc.
References mimosa::http::Request::contentLength(), mimosa::http::Request::contentType(), mimosa::stream::Buffer::data(), mimosa::uri::parseQuery(), mimosa::uri::percentDecode(), and mimosa::stream::Buffer::size().
    {
      if (parsed_form_)
        return form_;
      if (!::strcasecmp(contentType().c_str(), "application/x-www-form-urlencoded"))
      {
        parsed_form_ = true;
        stream::Buffer buffer(contentLength());
        int64_t total_rbytes = 0;
        while (total_rbytes < contentLength())
        {
          auto rbytes = stream_->read(buffer.data(), contentLength() - total_rbytes, 0);
          if (rbytes <= 0)
            return form_;
          total_rbytes += rbytes;
        }
        std::string decoded;
        uri::percentDecode(buffer.data(), buffer.size(), &decoded);
        uri::parseQuery(decoded.data(), decoded.size(), &form_);
      }
      return form_;
    }
mimosa::http::RequestReader::MIMOSA_DEF_PTR (RequestReader)
int64_t mimosa::http::RequestReader::read (char * data, uint64_t nbytes, runtime::Time timeout = 0) [virtual]
reads the body (PUT and POST)
Implements mimosa::stream::Stream.
Definition at line 45 of file request-reader.cc.
Referenced by flush().
    {
      uint64_t can_read = nbytes <= bytes_left_ ? nbytes : bytes_left_;
      int64_t rbytes = stream_->read(data, can_read, timeout);
      if (rbytes > 0)
        bytes_left_ -= rbytes;
      return rbytes;
    }
int64_t mimosa::http::RequestReader::write (const char * data, uint64_t nbytes, runtime::Time timeout = 0) [virtual]
Stream related stuff
Warning:
this should never be called, will abort
Implements mimosa::stream::Stream.
Definition at line 38 of file request-reader.cc.
    {
      assert(false && "invalid operation");
      return -1;
    }
Friends And Related Function Documentation
friend class ServerChannel [friend]
Definition at line 35 of file request-reader.hh.
The documentation for this class was generated from the following files:
mimosa/http/request-reader.hh
mimosa/http/request-reader.cc