mimosa: mimosa::rpc::Channel Class Reference
mimosa::rpc::Channel Class Reference
#include <channel.hh>
Public Types
enum Status { kOk, kClosed }
Public Member Functions
Channel (stream::BufferedStream::Ptr stream, ServiceMap::ConstPtr service_map)
Status status () const
void close ()
void sendCall (BasicCall::Ptr call)
void sendResponse (BasicCall::Ptr call)
void sendError (ErrorType error, uint32_t tag, TagOrigin tag_origin)
Friends
class Server
Detailed Description
Definition at line 18 of file channel.hh.
Member Enumeration Documentation
enum mimosa::rpc::Channel::Status
Enumerator:
kOk
kClosed
Definition at line 22 of file channel.hh.
      {
        kOk,
        kClosed,
      };
Constructor & Destructor Documentation
mimosa::rpc::Channel::Channel (stream::BufferedStream::Ptr stream, ServiceMap::ConstPtr service_map)
Definition at line 11 of file channel.cc.
References mimosa::runtime::Fiber::start().
      : stream_(stream),
        service_map_(service_map),
        scalls_(),
        rcalls_(),
        status_(kOk),
        write_queue_(),
        next_tag_(0)
    {
      Channel::Ptr channel(this);
      runtime::Fiber::start([channel]() { channel->readLoop(); });
      runtime::Fiber::start([channel]() { channel->writeLoop(); });
    }
Member Function Documentation
void mimosa::rpc::Channel::close ()
void mimosa::rpc::Channel::sendCall (BasicCall::Ptr call)
Definition at line 33 of file channel.cc.
References mimosa::rpc::kCall, mimosa::rpc::MsgCall::method_id_, mimosa::sync::Channel< T, QueueType >::push(), mimosa::rpc::MsgCall::rq_, mimosa::rpc::MsgCall::rq_size_, mimosa::rpc::MsgCall::service_id_, mimosa::rpc::MsgCall::tag_, and mimosa::rpc::Msg::type_.
    {
      call->setTag(nextTag());
      uint32_t rq_size  = call->request_->ByteSize();
      stream::Buffer::Ptr buffer = new stream::Buffer(rq_size + sizeof (MsgCall));
      MsgCall * msg    = reinterpret_cast<MsgCall *> (buffer->data());
      msg->type_       = kCall;
      msg->tag_        = htole32(call->tag());
      msg->service_id_ = htole32(call->serviceId());
      msg->method_id_  = htole32(call->methodId());
      msg->rq_size_    = htole32(rq_size);
      call->request_->SerializeToArray(msg->rq_, rq_size);
      {
        sync::Mutex::Locker locker(scalls_mutex_);
        while (true)
        {
          auto it = scalls_.find(call->tag());
          if (it == scalls_.end())
            break;
          call->setTag(nextTag());
          msg->tag_ = htole32(call->tag());
        }
        scalls_[call->tag()] = call;
      }
      write_queue_.push(buffer);
    }
void mimosa::rpc::Channel::sendError (ErrorType error, uint32_t tag, TagOrigin tag_origin)
Definition at line 79 of file channel.cc.
References mimosa::rpc::MsgError::error_, mimosa::rpc::kError, mimosa::sync::Channel< T, QueueType >::push(), mimosa::rpc::MsgError::tag_, mimosa::rpc::MsgError::tag_origin_, and mimosa::rpc::Msg::type_.
    {
      stream::Buffer::Ptr buffer = new stream::Buffer(sizeof (MsgError));
      MsgError * msg   = reinterpret_cast<MsgError *> (buffer->data());
      msg->type_       = kError;
      msg->error_      = error;
      msg->tag_        = htole32(tag);
      msg->tag_origin_ = tag_origin;
      write_queue_.push(buffer);
      {
        sync::Mutex::Locker locker(rcalls_mutex_);
        rcalls_.erase(tag);
      }
    }
void mimosa::rpc::Channel::sendResponse (BasicCall::Ptr call)
Definition at line 62 of file channel.cc.
References mimosa::rpc::kResult, mimosa::sync::Channel< T, QueueType >::push(), mimosa::rpc::MsgResult::rp_, mimosa::rpc::MsgResult::rp_size_, mimosa::rpc::MsgResult::tag_, and mimosa::rpc::Msg::type_.
    {
      uint32_t rp_size  = call->response_->ByteSize();
      stream::Buffer::Ptr buffer = new stream::Buffer(rp_size + sizeof (MsgResult));
      MsgResult * msg  = reinterpret_cast<MsgResult *> (buffer->data());
      msg->type_       = kResult;
      msg->tag_        = htole32(call->tag());
      msg->rp_size_    = htole32(rp_size);
      call->request_->SerializeToArray(msg->rp_, rp_size);
      write_queue_.push(buffer);
      {
        sync::Mutex::Locker locker(rcalls_mutex_);
        rcalls_.erase(call->tag());
      }
    }
Status mimosa::rpc::Channel::status () const [inline]
Definition at line 31 of file channel.hh.
{ return status_; }
Friends And Related Function Documentation
friend class Server [friend]
Definition at line 39 of file channel.hh.
The documentation for this class was generated from the following files:
mimosa/rpc/channel.hh
mimosa/rpc/channel.cc