mimosa: mimosa::net::Server Class Reference
mimosa::net::Server Class Reference
#include <server.hh>
Public Types
typedef Function< void(int fd)> AcceptHandler
Public Member Functions
Server ()
~Server ()
bool listenUnix (const std::string &path)
bool listenInet4 (uint16_t port, const struct::in_addr *interface=0)
bool listenInet6 (uint16_t port, const struct::in6_addr *interface=0)
void onAccept (AcceptHandler::Ptr handler)
void stop ()
Detailed Description
Definition at line 17 of file server.hh.
Member Typedef Documentation
typedef Function<void (int fd)> mimosa::net::Server::AcceptHandler
Definition at line 23 of file server.hh.
Constructor & Destructor Documentation
mimosa::net::Server::Server ()
Reimplemented in mimosa::http::Server, and mimosa::rpc::Server.
Definition at line 11 of file server.cc.
      : handler_(0),
        fd_(-1),
        stop_(false),
        accept_loop_(0)
    {
    }
mimosa::net::Server::~Server ()
Reimplemented in mimosa::http::Server.
Definition at line 19 of file server.cc.
References stop().
    {
      stop();
    }
Member Function Documentation
bool mimosa::net::Server::listenInet4 (uint16_t port, const struct::in_addr * interface = 0)
Definition at line 25 of file server.cc.
References mimosa::bind(), and stop().
    {
      stop();
      fd_ = ::socket(AF_INET, SOCK_STREAM, 0);
      if (fd_ < 0)
        return false;
      // enable reuse of the port after the close
      static const int enable = 1;
      ::setsockopt(fd_, SOL_SOCKET, SO_REUSEADDR, &enable, sizeof(enable));
      struct sockaddr_in addr;
      addr.sin_addr.s_addr = interface ? interface->s_addr : INADDR_ANY;
      addr.sin_family = AF_INET;
      addr.sin_port = ::htons(port);
      if (::bind(fd_, (struct sockaddr *)&addr, sizeof (addr)))
        goto failure;
      if (::listen(fd_, 10))
        goto failure;
      try {
        this->accept_loop_ = new runtime::Fiber(std::bind(&Server::acceptLoop, Server::Ptr(this)));
      } catch (...) {
        goto failure;
      }
      return true;
      failure:
      ::close(fd_);
      fd_ = -1;
      this->accept_loop_ = 0;
      return false;
    }
bool mimosa::net::Server::listenInet6 (uint16_t port, const struct::in6_addr * interface = 0)
bool mimosa::net::Server::listenUnix (const std::string & path)
void mimosa::net::Server::onAccept (AcceptHandler::Ptr handler) [inline]
Definition at line 28 of file server.hh.
Referenced by mimosa::rpc::Server::Server(), and mimosa::http::Server::Server().
{ handler_ = handler; }
void mimosa::net::Server::stop ()
Definition at line 75 of file server.cc.
References mimosa::runtime::milliseconds(), mimosa::runtime::time(), and mimosa::runtime::Fiber::timedJoin().
Referenced by listenInet4(), and ~Server().
    {
      if (fd_ >= 0)
      {
        assert(accept_loop_);
        stop_ = true;
        do {
          puts("canceling io...");
          ::melon_cancelio(fd_);
        } while (!accept_loop_->timedJoin(runtime::time() + runtime::milliseconds(1)));
        delete accept_loop_;
        ::melon_close(fd_);
        accept_loop_ = 0;
        fd_ = -1;
      }
      else
        assert(!accept_loop_);
    }
The documentation for this class was generated from the following files:
mimosa/net/server.hh
mimosa/net/server.cc