mimosa: mimosa::sync::SemaphoreHandle Class Reference
mimosa::sync::SemaphoreHandle Class Reference
#include <semaphore-handle.hh>
Public Member Functions
SemaphoreHandle (Semaphore &sem, int nb)
~SemaphoreHandle ()
void acquire (int nb=1)
void release (int nb=1) throw std
Detailed Description
Definition at line 8 of file semaphore-handle.hh.
Constructor & Destructor Documentation
mimosa::sync::SemaphoreHandle::SemaphoreHandle (Semaphore & sem, int nb) [inline]
Definition at line 11 of file semaphore-handle.hh.
References mimosa::sync::Semaphore::acquire().
        : sem_(sem),
          nb_(nb)
      {
        sem_.acquire(nb_);
      }
mimosa::sync::SemaphoreHandle::~SemaphoreHandle () [inline]
Definition at line 18 of file semaphore-handle.hh.
References mimosa::sync::Semaphore::release().
      {
        sem_.release(nb_);
      }
Member Function Documentation
void mimosa::sync::SemaphoreHandle::acquire (int nb = 1) [inline]
Definition at line 23 of file semaphore-handle.hh.
References mimosa::sync::Semaphore::acquire().
      {
        nb_ += nb;
        sem_.acquire(nb);
      }
void mimosa::sync::SemaphoreHandle::release (int nb = 1) [inline]
Definition at line 29 of file semaphore-handle.hh.
References mimosa::sync::Semaphore::release().
      {
        if (nb > nb_)
          throw std::logic_error("releasing more resources than acquired");
        nb_ -= nb;
        sem_.release(nb);
      }
The documentation for this class was generated from the following file:
mimosa/sync/semaphore-handle.hh