mimosa: mimosa::stream::CompressStream Class Reference
mimosa::stream::CompressStream Class Reference
#include <compress-stream.hh>
Public Member Functions
CompressStream (Stream::Ptr stream, int level=4)
virtual int64_t write (const char *data, uint64_t nbytes, runtime::Time timeout=0)
virtual int64_t read (char *data, uint64_t nbytes, runtime::Time timeout=0)
Detailed Description
Definition at line 10 of file compress-stream.hh.
Constructor & Destructor Documentation
mimosa::stream::CompressStream::CompressStream (Stream::Ptr stream, int level = 4)
Definition at line 10 of file compress-stream.cc.
      : stream_(stream),
        level_(level)
    {
    }
Member Function Documentation
int64_t mimosa::stream::CompressStream::read (char * data, uint64_t nbytes, runtime::Time timeout = 0) [virtual]
Implements mimosa::stream::Stream.
Definition at line 28 of file compress-stream.cc.
References mimosa::stream::Buffer::data().
    {
      uLong rsize = nbytes;
      while (::compressBound(rsize) > nbytes)
      {
        if (rsize == 0)
          return 0;
        --rsize;
      }
      Buffer buffer(rsize);
      rsize = stream_->read(buffer.data(), rsize, timeout);
      if (rsize == (uLong)-1)
        return -1;
      int ret = ::compress2((Bytef*)data, &nbytes, (Bytef*)buffer.data(), rsize, level_);
      if (ret != Z_OK)
        return -1; // kind of fatal error at this point if we don't save
                   // our input buffer.
      return nbytes;
    }
int64_t mimosa::stream::CompressStream::write (const char * data, uint64_t nbytes, runtime::Time timeout = 0) [virtual]
Implements mimosa::stream::Stream.
Definition at line 17 of file compress-stream.cc.
References mimosa::stream::Buffer::data(), and mimosa::stream::Buffer::size().
    {
      Buffer buffer(::compressBound(nbytes));
      uLong dest_len = buffer.size();
      int ret = ::compress2((Bytef*)buffer.data(), &dest_len, (Bytef*)data, nbytes, level_);
      if (ret != Z_OK)
        return -1;
      return stream_->write(buffer.data(), dest_len, timeout);
    }
The documentation for this class was generated from the following files:
mimosa/stream/compress-stream.hh
mimosa/stream/compress-stream.cc