mimosa: mimosa::rpc::Server Class Reference
mimosa::rpc::Server Class Reference
#include <server.hh>
Public Member Functions
MIMOSA_DEF_PTR (Server)
Server ()
ServiceMap::ConstPtr serviceMap () const
void setServiceMap (ServiceMap::ConstPtr service_map)
Static Public Member Functions
static void serve (Server::Ptr server, int fd)
Protected Attributes
ServiceMap::ConstPtr service_map_
Detailed Description
Definition at line 12 of file server.hh.
Constructor & Destructor Documentation
mimosa::rpc::Server::Server ()
Reimplemented from mimosa::net::Server.
Definition at line 10 of file server.cc.
References mimosa::bind(), mimosa::net::Server::onAccept(), and serve().
    {
      this->onAccept(new AcceptHandler(
                       std::bind(&Server::serve, Server::Ptr(this),
                                 std::placeholders::_1)));
    }
Member Function Documentation
mimosa::rpc::Server::MIMOSA_DEF_PTR (Server)
void mimosa::rpc::Server::serve (Server::Ptr server, int fd) [static]
Definition at line 18 of file server.cc.
References mimosa::runtime::Fiber::start().
Referenced by Server().
    {
      stream::FdStream::Ptr stream = new stream::FdStream(fd);
      Channel::Ptr channel = new Channel(stream, server->service_map_);
      runtime::Fiber::start([channel]() { channel->readLoop(); });
      runtime::Fiber::start([channel]() { channel->writeLoop(); });
    }
ServiceMap::ConstPtr mimosa::rpc::Server::serviceMap () const [inline]
Definition at line 20 of file server.hh.
References service_map_.
{ return service_map_; }
void mimosa::rpc::Server::setServiceMap (ServiceMap::ConstPtr service_map) [inline]
Definition at line 21 of file server.hh.
References service_map_.
Referenced by main().
      { service_map_ = service_map; }
Field Documentation
ServiceMap::ConstPtr mimosa::rpc::Server::service_map_ [protected]
Definition at line 27 of file server.hh.
Referenced by serviceMap(), and setServiceMap().
The documentation for this class was generated from the following files:
mimosa/rpc/server.hh
mimosa/rpc/server.cc