mimosa: mimosa::stream::Stream Class Reference
mimosa::stream::Stream Class Reference
#include <stream.hh>
Public Member Functions
virtual ~Stream ()
virtual int64_t write (const char *data, uint64_t nbytes, runtime::Time timeout=0)=0
virtual int64_t writev (const struct iovec *iov, int iovcnt, runtime::Time timeout=0)
virtual int64_t read (char *data, uint64_t nbytes, runtime::Time timeout=0)=0
virtual int64_t readv (const struct iovec *iov, int iovcnt, runtime::Time timeout=0)
virtual bool flush (runtime::Time)
int64_t loopRead (char *data, uint64_t nbytes, runtime::Time timeout=0)
int64_t loopWrite (const char *data, uint64_t nbytes, runtime::Time timeout=0)
Detailed Description
Definition at line 17 of file stream.hh.
Constructor & Destructor Documentation
virtual mimosa::stream::Stream::~Stream () [inline, virtual]
Definition at line 21 of file stream.hh.
{}
Member Function Documentation
virtual bool mimosa::stream::Stream::flush (runtime::Time) [inline, virtual]
flushes the write buffer
Reimplemented in mimosa::http::ResponseWriter, mimosa::http::RequestReader, and mimosa::stream::BufferedStream.
Definition at line 29 of file stream.hh.
{ return true; }
int64_t mimosa::stream::Stream::loopRead (char * data, uint64_t nbytes, runtime::Time timeout = 0)
Definition at line 46 of file stream.cc.
References read().
    {
      uint64_t bytes_left = nbytes;
      do {
        auto bytes = read(data, bytes_left, timeout);
        if (bytes <= 0)
        {
          if (errno == EAGAIN)
            continue;
          return nbytes - bytes_left;
        }
        data       += bytes;
        bytes_left -= bytes;
      } while (nbytes > 0);
      return nbytes;
    }
int64_t mimosa::stream::Stream::loopWrite (const char * data, uint64_t nbytes, runtime::Time timeout = 0)
Definition at line 64 of file stream.cc.
References write().
    {
      uint64_t bytes_left = nbytes;
      do {
        auto bytes = write(data, bytes_left, timeout);
        if (bytes <= 0)
        {
          if (errno == EAGAIN)
            continue;
          return nbytes - bytes_left;
        }
        data       += bytes;
        bytes_left -= bytes;
      } while (nbytes > 0);
      return nbytes;
    }
virtual int64_t mimosa::stream::Stream::read (char * data, uint64_t nbytes, runtime::Time timeout = 0) [pure virtual]
Implemented in mimosa::http::ResponseWriter, mimosa::http::RequestReader, mimosa::stream::DirectFdStream, mimosa::stream::BufferedStream, mimosa::stream::TlsStream, mimosa::stream::CompressStream, and mimosa::stream::LimitedStream.
Referenced by mimosa::stream::copy(), loopRead(), and readv().
int64_t mimosa::stream::Stream::readv (const struct iovec * iov, int iovcnt, runtime::Time timeout = 0) [virtual]
Reimplemented in mimosa::stream::DirectFdStream.
Definition at line 28 of file stream.cc.
References read().
    {
      int64_t bytes = 0;
      for (int i = 0; i < iovcnt; ++i)
      {
        int64_t ret = read((char *)iov[i].iov_base, iov[i].iov_len, timeout);
        if (ret <= 0)
        {
          if (bytes > 0)
            return bytes;
          return ret;
        }
        bytes += ret;
      }
      return bytes;
    }
virtual int64_t mimosa::stream::Stream::write (const char * data, uint64_t nbytes, runtime::Time timeout = 0) [pure virtual]
Implemented in mimosa::http::ResponseWriter, mimosa::http::RequestReader, mimosa::stream::DirectFdStream, mimosa::stream::BufferedStream, mimosa::stream::TlsStream, mimosa::stream::CompressStream, and mimosa::stream::LimitedStream.
Referenced by mimosa::stream::copy(), loopWrite(), and writev().
int64_t mimosa::stream::Stream::writev (const struct iovec * iov, int iovcnt, runtime::Time timeout = 0) [virtual]
Reimplemented in mimosa::stream::DirectFdStream.
Definition at line 10 of file stream.cc.
References write().
    {
      int64_t bytes = 0;
      for (int i = 0; i < iovcnt; ++i)
      {
        int64_t ret = write((const char *)iov[i].iov_base, iov[i].iov_len, timeout);
        if (ret <= 0)
        {
          if (bytes > 0)
            return bytes;
          return ret;
        }
        bytes += ret;
      }
      return bytes;
    }
The documentation for this class was generated from the following files:
mimosa/stream/stream.hh
mimosa/stream/stream.cc