mimosa: mimosa::stream::BufferedStream Class Reference
mimosa::stream::BufferedStream Class Reference
#include <buffered-stream.hh>
Public Member Functions
MIMOSA_DEF_PTR (BufferedStream)
BufferedStream (Stream::Ptr stream, uint64_t buffer_size=64 *1024)
virtual ~BufferedStream ()
virtual int64_t write (const char *data, uint64_t nbytes, runtime::Time timeout=0)
virtual int64_t read (char *data, uint64_t nbytes, runtime::Time timeout=0)
virtual bool flush (runtime::Time timeout=0)
Buffer::Ptr read (runtime::Time timeout=0)
Buffer::Ptr read (uint64_t buffer_size, runtime::Time timeout=0)
Buffer::Ptr readUntil (const char *const str, uint64_t max_size=0, runtime::Time timeout=0, bool *found=nullptr)
Detailed Description
Definition at line 14 of file buffered-stream.hh.
Constructor & Destructor Documentation
mimosa::stream::BufferedStream::BufferedStream (Stream::Ptr stream, uint64_t buffer_size = 64 * 1024)
Definition at line 10 of file buffered-stream.cc.
      : stream_(stream),
        buffer_size_(buffer_size),
        wbuffers_(),
        wpos_(0),
        wappend_(0),
        rbuffer_(),
        rpos_(0),
        rappend_(0)
    {
    }
mimosa::stream::BufferedStream::~BufferedStream () [virtual]
Definition at line 22 of file buffered-stream.cc.
    {
    }
Member Function Documentation
bool mimosa::stream::BufferedStream::flush (runtime::Time = 0) [virtual]
flushes the write buffer
Reimplemented from mimosa::stream::Stream.
Definition at line 248 of file buffered-stream.cc.
References mimosa::container::IntrusiveSlist< T, Ptr, Member >::begin(), mimosa::container::IntrusiveSlist< T, Ptr, Member >::empty(), mimosa::container::IntrusiveSlist< T, Ptr, Member >::end(), mimosa::container::IntrusiveSlist< T, Ptr, Member >::pop(), and mimosa::container::IntrusiveSlist< T, Ptr, Member >::size().
    {
      while (!wbuffers_.empty())
      {
        // setup iov
        const  int           iov_cnt = wbuffers_.size();
        struct iovec         iov[iov_cnt];
        struct iovec * const iov_last = iov + iov_cnt - 1;
        struct iovec *       p        = iov;
        for (auto it = wbuffers_.begin(); it != wbuffers_.end(); ++it, ++p)
        {
          p->iov_base = it->data();
          p->iov_len  = it->size();
          if (p == iov)
          {
            p->iov_base += wpos_;
            p->iov_len  -= wpos_;
          }
          if (p == iov_last)
            p->iov_len -= it->size() - wappend_;
        }
        // write and remove completed buffers
        int64_t wbytes = stream_->writev(iov, iov_cnt, timeout);
        if (wbytes < 0)
          return false;
        // remove completed buffers
        p = iov;
        for (auto it = wbuffers_.begin(); it != wbuffers_.end(); ++it, ++p)
        {
          if (wbytes >= p->iov_len)
          {
            wbytes -= p->iov_len;
            wbuffers_.pop();
            wpos_ = 0;
          }
          else
          {
            wpos_ = wbytes;
            wbytes = 0;
            break;
          }
        }
      }
      return true;
    }
mimosa::stream::BufferedStream::MIMOSA_DEF_PTR (BufferedStream)
int64_t mimosa::stream::BufferedStream::read (char * data, uint64_t nbytes, runtime::Time timeout = 0) [virtual]
Implements mimosa::stream::Stream.
Definition at line 133 of file buffered-stream.cc.
Referenced by readUntil().
    {
      if (rappend_ == rpos_)
      {
        if (!rbuffer_)
          rbuffer_ = new Buffer(buffer_size_);
        else if (rbuffer_->size() != buffer_size_)
          rbuffer_->resize(buffer_size_);
        rpos_    = 0;
        rappend_ = 0;
        int64_t rbytes = stream_->read(rbuffer_->data(), rbuffer_->size(), timeout);
        if (rbytes <= 0)
          return rbytes;
        rappend_ = rbytes;
      }
      assert(rappend_ > rpos_);
      assert(rbuffer_);
      nbytes = nbytes <= rappend_ - rpos_ ? nbytes : rappend_ - rpos_;
      ::memcpy(data, rbuffer_->data(), nbytes);
      rpos_ += nbytes;
      if (rpos_ == rappend_)
      {
        rpos_    = 0;
        rappend_ = 0;
      }
      return nbytes;
    }
Buffer::Ptr mimosa::stream::BufferedStream::read (runtime::Time timeout = 0) [inline]
Zero copy stuff
Definition at line 28 of file buffered-stream.hh.
References read().
Referenced by read().
{ return read(buffer_size_, timeout); }
Buffer::Ptr mimosa::stream::BufferedStream::read (uint64_t buffer_size, runtime::Time timeout = 0)
Zero copy stuff
Definition at line 163 of file buffered-stream.cc.
    {
      if (rappend_ > rpos_)
      {
        assert(rbuffer_);
        ::memmove(rbuffer_->data(), rbuffer_->data() + rpos_, rappend_ - rpos_);
        rbuffer_->resize(rappend_ - rpos_);
        auto tmp = rbuffer_;
        rbuffer_ = nullptr;
        rappend_ = 0;
        rpos_ = 0;
        return tmp;
      }
      if (!rbuffer_)
        rbuffer_ = new Buffer(buffer_size);
      int64_t bytes = stream_->read(rbuffer_->data(), rbuffer_->size(), timeout);
      if (bytes <= 0)
        return nullptr;
      rbuffer_->resize(bytes);
      auto tmp = rbuffer_;
      rbuffer_ = nullptr;
      return tmp;
    }
Buffer::Ptr mimosa::stream::BufferedStream::readUntil (const char *const str, uint64_t max_size = 0, runtime::Time timeout = 0, bool * found = nullptr)
Helpers
Parameters:
max_size if str is not reached until max_size, returns nullptr and errno is set to EFBIG
str the string to search
Returns:
a valid buffer on success, null otherwise.
Definition at line 189 of file buffered-stream.cc.
References read().
    {
      Buffer::Ptr buffer;
      size_t      str_len = strlen(str);
      if (found)
        *found = false;
      while (true)
      {
        if (max_size > 0 && buffer && buffer->size() > max_size)
        {
          errno = EFBIG;
          return nullptr;
        }
        Buffer::Ptr tmp_buffer = read(buffer_size_, timeout);
        if (!tmp_buffer || tmp_buffer->size() == 0)
        {
          assert(!rbuffer_ || rappend_ == 0);
          rbuffer_ = buffer;
          rappend_ = buffer ? buffer->size() : 0;
          return nullptr;
        }
        if (buffer)
        {
          buffer->resize(buffer->size() + tmp_buffer->size());
          memcpy(buffer->data() + buffer->size() - tmp_buffer->size(),
                 tmp_buffer->data(), tmp_buffer->size());
        }
        else
          buffer = tmp_buffer;
        int64_t offset = buffer->size() - tmp_buffer->size() - str_len;
        const char * found_str = ::strstr(buffer->data() + (offset > 0 ? offset : 0), str);
        if (found_str)
        {
          assert(!rbuffer_);
          if (found)
            *found = true;
          /* setup the remaining read buffer */
          rbuffer_ = new Buffer(buffer_size_);
          const int64_t remain_size = found_str + str_len - buffer->data();
          rappend_ = buffer->size() - remain_size;
          memcpy(rbuffer_->data(), buffer->data() + remain_size, rappend_);
          /* resize the return buffer */
          buffer->resize(found_str - buffer->data() + str_len);
          return buffer;
        }
      }
    }
int64_t mimosa::stream::BufferedStream::write (const char * data, uint64_t nbytes, runtime::Time timeout = 0) [virtual]
Implements mimosa::stream::Stream.
Definition at line 71 of file buffered-stream.cc.
References mimosa::container::IntrusiveSlist< T, Ptr, Member >::begin(), mimosa::container::IntrusiveSlist< T, Ptr, Member >::end(), mimosa::container::IntrusiveSlist< T, Ptr, Member >::pop(), and mimosa::container::IntrusiveSlist< T, Ptr, Member >::size().
    {
      const auto nbytes_orig = nbytes;
      // while we have more than buffer_size_ to write
      while (nbytes + readyWrite() >= buffer_size_)
      {
        // setup iov
        const  int     iov_cnt = wbuffers_.size() + 1;
        struct iovec   iov[iov_cnt];
        struct iovec * p = iov;
        for (auto it = wbuffers_.begin(); it != wbuffers_.end(); ++it, ++p)
        {
          p->iov_base = it->data();
          p->iov_len  = it->size();
          if (p == iov)
          {
            p->iov_base += wpos_;
            p->iov_len  -= wpos_;
          }
          if (p == iov + wbuffers_.size() - 1)
            p->iov_len -= it->size() - wappend_;
        }
        iov[iov_cnt - 1].iov_base = const_cast<char *>(data);
        iov[iov_cnt - 1].iov_len  = nbytes;
        // write and remove completed buffers
        int64_t wbytes = stream_->writev(iov, iov_cnt, timeout);
        if (wbytes < 0)
        {
          if (nbytes_orig == nbytes)
            return -1;
          return nbytes_orig - nbytes;
        }
        // remove completed buffers
        p = iov;
        for (auto it = wbuffers_.begin(); it != wbuffers_.end(); ++it, ++p)
        {
          if (wbytes >= p->iov_len)
          {
            wbytes -= p->iov_len;
            wbuffers_.pop();
            wpos_ = 0;
          }
          else
          {
            wpos_ = wbytes;
            wbytes = 0;
            break;
          }
        }
        nbytes -= wbytes;
      }
      if (nbytes > 0)
        append(data, nbytes);
      return nbytes_orig;
    }
The documentation for this class was generated from the following files:
mimosa/stream/buffered-stream.hh
mimosa/stream/buffered-stream.cc