mimosa: mimosa::sync::Barrier Class Reference
mimosa::sync::Barrier Class Reference
#include <barrier.hh>
Public Member Functions
Barrier (uint16_t nb) throw std
~Barrier ()
void add (uint16_t nb=1)
void release (uint16_t nb=1)
void wait ()
Detailed Description
Definition at line 14 of file barrier.hh.
Constructor & Destructor Documentation
mimosa::sync::Barrier::Barrier (uint16_t nb) [inline]
Definition at line 17 of file barrier.hh.
        : barrier_(::melon_barrier_new(nb))
      {
        if (!barrier_)
          throw std::bad_alloc;
      }
mimosa::sync::Barrier::~Barrier () [inline]
Definition at line 24 of file barrier.hh.
{ ::melon_barrier_destroy(barrier_); }
Member Function Documentation
void mimosa::sync::Barrier::add (uint16_t nb = 1) [inline]
Definition at line 25 of file barrier.hh.
Referenced by mimosa::sync::BarrierHandle::BarrierHandle().
{ ::melon_barrier_add(barrier_, nb); }
void mimosa::sync::Barrier::release (uint16_t nb = 1) [inline]
Definition at line 26 of file barrier.hh.
Referenced by mimosa::sync::BarrierHandle::~BarrierHandle().
{ ::melon_barrier_release(barrier_, nb); }
void mimosa::sync::Barrier::wait () [inline]
Definition at line 27 of file barrier.hh.
Referenced by mimosa::sync::BarrierHandle::wait().
{ ::melon_barrier_wait(barrier_); }
The documentation for this class was generated from the following file:
mimosa/sync/barrier.hh