mimosa: mimosa::http::Server Class Reference
mimosa::http::Server Class Reference
#include <server.hh>
Public Member Functions
MIMOSA_DEF_PTR (Server)
Server ()
~Server ()
void setHandler (Handler::Ptr handler)
void setSecure (const std::string &cert_file, const std::string &key_file)
Detailed Description
Definition at line 14 of file server.hh.
Constructor & Destructor Documentation
mimosa::http::Server::Server ()
Reimplemented from mimosa::net::Server.
Definition at line 13 of file server.cc.
References mimosa::bind(), and mimosa::net::Server::onAccept().
      : read_timeout_(0),
        write_timeout_(0),
        handler_(),
        x509_cred_(nullptr),
        priority_cache_(nullptr),
        dh_params_(nullptr)
    {
      ::gnutls_priority_init(&priority_cache_, "NORMAL", NULL);
      ::gnutls_dh_params_init(&dh_params_);
      ::gnutls_dh_params_generate2(dh_params_, 1024);
      onAccept(new AcceptHandler(std::bind(&Server::newClient, Server::Ptr(this),
                                           std::placeholders::_1)));
    }
mimosa::http::Server::~Server ()
Reimplemented from mimosa::net::Server.
Definition at line 28 of file server.cc.
    {
      ::gnutls_priority_deinit(priority_cache_);
      ::gnutls_dh_params_deinit(dh_params_);
      if (x509_cred_)
        ::gnutls_certificate_free_credentials(x509_cred_);
    }
Member Function Documentation
mimosa::http::Server::MIMOSA_DEF_PTR (Server)
void mimosa::http::Server::setHandler (Handler::Ptr handler) [inline]
Definition at line 22 of file server.hh.
Referenced by main().
{ handler_ = handler; }
void mimosa::http::Server::setSecure (const std::string & cert_file, const std::string & key_file)
Definition at line 63 of file server.cc.
    {
      if (!x509_cred_)
        ::gnutls_certificate_allocate_credentials(&x509_cred_);
      ::gnutls_certificate_set_x509_key_file(x509_cred_, cert_file.c_str(), key_file.c_str(),
                                             GNUTLS_X509_FMT_PEM);
      ::gnutls_certificate_set_dh_params(x509_cred_, dh_params_);
    }
The documentation for this class was generated from the following files:
mimosa/http/server.hh
mimosa/http/server.cc