mimosa: mimosa::runtime::Fiber Class Reference
mimosa::runtime::Fiber Class Reference
#include <fiber.hh>
Public Member Functions
template<typename T >
Fiber (void *(*fct)(T *), T *ctx)
Fiber (std::function< void()> &&fct)
~Fiber ()
void join ()
bool tryJoin ()
bool timedJoin (Time timeout)
void detach ()
Static Public Member Functions
template<typename T >
static void start (void *(*fct)(T *), T *ctx)
static void start (std::function< void()> &&fct)
Detailed Description
Definition at line 16 of file fiber.hh.
Constructor & Destructor Documentation
template<typename T > mimosa::runtime::Fiber::Fiber (void *(*)(T *) fct, T * ctx) [inline]
Definition at line 31 of file fiber.hh.
        : fiber_(::melon_fiber_start(reinterpret_cast<void*(*)(void*)>(fct),
                                     static_cast<void*>(ctx)))
      {
        if (!fiber_)
          throw std::runtime_error("failed to start new fiber");
      }
mimosa::runtime::Fiber::Fiber (std::function< void()> && fct)
Definition at line 20 of file fiber.cc.
References mimosa::runtime::startWrapper().
      : fiber_(0)
    {
      auto cb = new std::function<void ()>(fct);
      fiber_ = ::melon_fiber_start(reinterpret_cast<void*(*)(void*)>(startWrapper),
                                   static_cast<void*>(cb));
      if (!fiber_)
        throw std::runtime_error("failed to start new fiber");
    }
mimosa::runtime::Fiber::~Fiber ()
Definition at line 30 of file fiber.cc.
References detach().
    {
      detach();
    }
Member Function Documentation
void mimosa::runtime::Fiber::detach ()
Definition at line 65 of file fiber.cc.
Referenced by ~Fiber().
    {
      if (!fiber_)
        return;
      ::melon_fiber_detach(fiber_);
      fiber_ = 0;
    }
void mimosa::runtime::Fiber::join ()
Definition at line 35 of file fiber.cc.
    {
      if (!fiber_)
        return;
      ::melon_fiber_join(fiber_, NULL);
      fiber_ = 0;
    }
template<typename T > static void mimosa::runtime::Fiber::start (void *(*)(T *) fct, T * ctx) [inline, static]
Definition at line 21 of file fiber.hh.
Referenced by mimosa::rpc::Channel::Channel(), mimosa::deinit(), mimosa::init(), mimosa::rpc::Server::serve(), and start().
      {
        if (::melon_fiber_startlight(reinterpret_cast<void*(*)(void*)>(fct),
                                     static_cast<void*>(ctx)))
          throw std::runtime_error("failed to start new fiber");
      }
void mimosa::runtime::Fiber::start (std::function< void()> && fct) [static]
Definition at line 14 of file fiber.cc.
References start(), and mimosa::runtime::startWrapper().
    {
      auto cb = new std::function<void ()>(fct);
      Fiber::start(startWrapper, cb);
    }
bool mimosa::runtime::Fiber::timedJoin (Time timeout)
Definition at line 54 of file fiber.cc.
Referenced by mimosa::net::Server::stop().
    {
      if (!fiber_)
        return false;
      if (::melon_fiber_timedjoin(fiber_, NULL, timeout))
        return false;
      fiber_ = 0;
      return true;
    }
bool mimosa::runtime::Fiber::tryJoin ()
Definition at line 43 of file fiber.cc.
    {
      if (!fiber_)
        return false;
      if (::melon_fiber_tryjoin(fiber_, NULL))
        return false;
      fiber_ = 0;
      return true;
    }
The documentation for this class was generated from the following files:
mimosa/runtime/fiber.hh
mimosa/runtime/fiber.cc