mimosa: mimosa::http::Cookie Class Reference
mimosa::http::Cookie Class Reference
#include <cookie.hh>
Public Types
typedef
container::IntrusiveSlist
< Cookie, Cookie::Ptr,&Cookie::next_ > Slist
Public Member Functions
Cookie ()
void setDomain (const std::string &domain)
const std::string & domain () const
void setExpires (const std::string &expires)
const std::string & expires () const
void setPath (const std::string &path)
const std::string & path () const
void setKey (const std::string &key)
const std::string & key () const
void setValue (const std::string &value)
const std::string & value () const
void setSecure (bool enable)
bool isSecure () const
void setHttpOnly (bool enable)
bool isHttpOnly () const
Data Fields
container::IntrusiveSlistHook
< Cookie::Ptr > next_
Detailed Description
Definition at line 13 of file cookie.hh.
Member Typedef Documentation
typedef container::IntrusiveSlist<Cookie, Cookie::Ptr, &Cookie::next_> mimosa::http::Cookie::Slist
Definition at line 17 of file cookie.hh.
Constructor & Destructor Documentation
mimosa::http::Cookie::Cookie ()
Definition at line 7 of file cookie.cc.
      : key_(),
        value_(),
        is_secure_(false)
    {
    }
Member Function Documentation
const std::string& mimosa::http::Cookie::domain () const [inline]
Definition at line 22 of file cookie.hh.
Referenced by setDomain().
{ return domain_; }
const std::string& mimosa::http::Cookie::expires () const [inline]
Definition at line 24 of file cookie.hh.
Referenced by setExpires().
{ return expires_; }
bool mimosa::http::Cookie::isHttpOnly () const [inline]
Definition at line 34 of file cookie.hh.
{ return is_http_only_; }
bool mimosa::http::Cookie::isSecure () const [inline]
Definition at line 32 of file cookie.hh.
{ return is_secure_; }
const std::string& mimosa::http::Cookie::key () const [inline]
Definition at line 28 of file cookie.hh.
Referenced by setKey().
{ return key_; }
const std::string& mimosa::http::Cookie::path () const [inline]
Definition at line 26 of file cookie.hh.
Referenced by setPath().
{ return path_; }
void mimosa::http::Cookie::setDomain (const std::string & domain) [inline]
Definition at line 21 of file cookie.hh.
References domain().
{ domain_ = domain; }
void mimosa::http::Cookie::setExpires (const std::string & expires) [inline]
Definition at line 23 of file cookie.hh.
References expires().
{ expires_ = expires; }
void mimosa::http::Cookie::setHttpOnly (bool enable) [inline]
Definition at line 33 of file cookie.hh.
{ is_http_only_ = enable; }
void mimosa::http::Cookie::setKey (const std::string & key) [inline]
Definition at line 27 of file cookie.hh.
References key().
{ key_ = key; }
void mimosa::http::Cookie::setPath (const std::string & path) [inline]
Definition at line 25 of file cookie.hh.
References path().
{ path_ = path; }
void mimosa::http::Cookie::setSecure (bool enable) [inline]
Definition at line 31 of file cookie.hh.
{ is_secure_ = enable; }
void mimosa::http::Cookie::setValue (const std::string & value) [inline]
Definition at line 29 of file cookie.hh.
References value().
{ value_ = value; }
const std::string& mimosa::http::Cookie::value () const [inline]
Definition at line 30 of file cookie.hh.
Referenced by setValue().
{ return value_; }
Field Documentation
container::IntrusiveSlistHook<Cookie::Ptr> mimosa::http::Cookie::next_
Definition at line 16 of file cookie.hh.
The documentation for this class was generated from the following files:
mimosa/http/cookie.hh
mimosa/http/cookie.cc