mimosa: mimosa::http::ErrorHandler Class Reference
mimosa::http::ErrorHandler Class Reference
#include <error-handler.hh>
Public Member Functions
virtual ~ErrorHandler ()
virtual bool handle (Request &request, ResponseWriter &response, Status status) const
Static Public Member Functions
static bool basicResponse (Request &request, ResponseWriter &response, Status status)
Detailed Description
Definition at line 11 of file error-handler.hh.
Constructor & Destructor Documentation
virtual mimosa::http::ErrorHandler::~ErrorHandler () [inline, virtual]
Definition at line 14 of file error-handler.hh.
{}
Member Function Documentation
bool mimosa::http::ErrorHandler::basicResponse (Request & request, ResponseWriter & response, Status status) [static]
Definition at line 10 of file error-handler.cc.
References mimosa::http::Response::status_, mimosa::http::statusToString(), and mimosa::http::ResponseWriter::write().
Referenced by handle(), and mimosa::http::FsHandler::handle().
    {
      std::ostringstream os;
      os << "<html><head><title>Error " << status << " - "
         << statusToString(status) << "</title></head><body>Error "
         << status << " - " << statusToString(status) << "</body></html>";
      response.status_ = status;
      auto str = os.str();
      response.write(str.data(), str.size());
      return true;
    }
virtual bool mimosa::http::ErrorHandler::handle (Request & request, ResponseWriter & response, Status status) const [inline, virtual]
Definition at line 16 of file error-handler.hh.
References basicResponse().
      {
        return basicResponse(request, response, status);
      }
The documentation for this class was generated from the following files:
mimosa/http/error-handler.hh
mimosa/http/error-handler.cc