mimosa: mimosa::sync::Semaphore Class Reference
mimosa::sync::Semaphore Class Reference
#include <semaphore.hh>
Public Member Functions
Semaphore (int nb) throw std
~Semaphore ()
void acquire (int nb)
bool tryAcquire (int nb)
bool timedAcquire (int nb)
void release (int nb)
Detailed Description
Definition at line 14 of file semaphore.hh.
Constructor & Destructor Documentation
mimosa::sync::Semaphore::Semaphore (int nb) [inline]
Definition at line 17 of file semaphore.hh.
        : sem_(::melon_sem_new(nb))
      {
        if (!sem_)
          throw std::bad_alloc;
      }
mimosa::sync::Semaphore::~Semaphore () [inline]
Definition at line 24 of file semaphore.hh.
      {
        ::melon_sem_destroy(sem_);
      }
Member Function Documentation
void mimosa::sync::Semaphore::acquire (int nb) [inline]
Definition at line 29 of file semaphore.hh.
Referenced by mimosa::sync::SemaphoreHandle::acquire(), and mimosa::sync::SemaphoreHandle::SemaphoreHandle().
{ ::melon_sem_acquire(sem_, nb); }
void mimosa::sync::Semaphore::release (int nb) [inline]
Definition at line 32 of file semaphore.hh.
Referenced by mimosa::sync::SemaphoreHandle::release(), and mimosa::sync::SemaphoreHandle::~SemaphoreHandle().
{ ::melon_sem_release(sem_, nb); }
bool mimosa::sync::Semaphore::timedAcquire (int nb) [inline]
Definition at line 31 of file semaphore.hh.
{ return !::melon_sem_timedacquire(sem_, nb); }
bool mimosa::sync::Semaphore::tryAcquire (int nb) [inline]
Definition at line 30 of file semaphore.hh.
{ return !::melon_sem_tryacquire(sem_, nb); }
The documentation for this class was generated from the following file:
mimosa/sync/semaphore.hh