mimosa: mimosa::stream::Buffer Class Reference
mimosa::stream::Buffer Class Reference
#include <buffer.hh>
Public Types
typedef
container::IntrusiveSlist
< Buffer, Buffer::Ptr,&Buffer::next_ > Slist
Public Member Functions
Buffer (uint64_t size=64 *1024)
Buffer (const char *data, uint64_t size)
~Buffer ()
uint64_t size () const
char * data ()
const char * data () const
void resize (uint64_t size)
Friends
class container::IntrusiveSlist< Buffer, Buffer::Ptr,&Buffer::next_ >
Detailed Description
the real size of the buffer is size + 4. So it's null terminated and you can pass the buffer to flex without duplicating it.
Definition at line 18 of file buffer.hh.
Member Typedef Documentation
typedef container::IntrusiveSlist<Buffer, Buffer::Ptr, &Buffer::next_> mimosa::stream::Buffer::Slist
Definition at line 37 of file buffer.hh.
Constructor & Destructor Documentation
mimosa::stream::Buffer::Buffer (uint64_t size = 64 * 1024)
Definition at line 10 of file buffer.cc.
      : size_(size),
        data_(reinterpret_cast<char *>(::malloc(size + 4)))
    {
      data_[size_ + 3] = 0;
      data_[size_ + 2] = 0;
      data_[size_ + 1] = 0;
      data_[size_]     = 0;
    }
mimosa::stream::Buffer::Buffer (const char * data, uint64_t size)
constructs a copy of the data buffer
Definition at line 20 of file buffer.cc.
      : size_(size),
        data_(reinterpret_cast<char *>(::malloc(size + 4)))
    {
      ::memcpy(data_, data, size);
      data_[size_ + 3] = 0;
      data_[size_ + 2] = 0;
      data_[size_ + 1] = 0;
      data_[size_]     = 0;
    }
mimosa::stream::Buffer::~Buffer ()
Definition at line 31 of file buffer.cc.
    {
      free(data_);
      size_ = 0;
      data_ = nullptr;
    }
Member Function Documentation
char* mimosa::stream::Buffer::data () [inline]
Definition at line 27 of file buffer.hh.
Referenced by mimosa::http::RequestReader::flush(), mimosa::http::RequestReader::form(), mimosa::stream::CompressStream::read(), and mimosa::stream::CompressStream::write().
{ return data_; }
const char* mimosa::stream::Buffer::data () const [inline]
Definition at line 28 of file buffer.hh.
{ return data_; }
void mimosa::stream::Buffer::resize (uint64_t size)
Definition at line 39 of file buffer.cc.
References size().
    {
      data_            = reinterpret_cast<char *>(::realloc(data_, size + 4));
      size_            = size;
      data_[size_ + 3] = 0;
      data_[size_ + 2] = 0;
      data_[size_ + 1] = 0;
      data_[size_]     = 0;
    }
uint64_t mimosa::stream::Buffer::size () const [inline]
Definition at line 26 of file buffer.hh.
Referenced by mimosa::http::RequestReader::flush(), mimosa::http::RequestReader::form(), resize(), and mimosa::stream::CompressStream::write().
{ return size_; }
Friends And Related Function Documentation
friend class container::IntrusiveSlist< Buffer, Buffer::Ptr,&Buffer::next_ > [friend]
Definition at line 38 of file buffer.hh.
The documentation for this class was generated from the following files:
mimosa/stream/buffer.hh
mimosa/stream/buffer.cc