mimosa: mimosa::http::FsHandler Class Reference
mimosa::http::FsHandler Class Reference
#include <fs-handler.hh>
Public Member Functions
FsHandler (const std::string &root, int nskip, bool enable_readdir=false)
virtual bool handle (RequestReader &request, ResponseWriter &response) const
Detailed Description
Definition at line 12 of file fs-handler.hh.
Constructor & Destructor Documentation
mimosa::http::FsHandler::FsHandler (const std::string & root, int nskip, bool enable_readdir = false)
Definition at line 18 of file fs-handler.cc.
      : root_(root),
        nskip_(nskip),
        can_readdir_(enable_readdir)
    {
    }
Member Function Documentation
bool mimosa::http::FsHandler::handle (RequestReader & request, ResponseWriter & response) const [virtual]
This is the handle method. It must be thread-safe.
Implements mimosa::http::Handler.
Definition at line 26 of file fs-handler.cc.
References mimosa::http::ErrorHandler::basicResponse(), mimosa::string::StringRef::find(), mimosa::http::kStatusForbidden, mimosa::http::kStatusInternalServerError, mimosa::http::kStatusNotFound, mimosa::http::Request::location(), and mimosa::string::StringRef::npos.
    {
      string::StringRef path(request.location());
      for (auto nskip = nskip_; nskip > 0; --nskip)
      {
        auto pos = path.find('/', 1);
        if (pos == string::StringRef::npos)
        {
          if (nskip == 1 && path.size() > 1) // our location is root and is not terminated by '/'
          {
            path = string::StringRef("/");
            break;
          }
          else
            // TODO: error reporting
            return ErrorHandler::basicResponse(request, response, kStatusInternalServerError);
        }
        path = path.substr(pos);
      }
      // TODO: check every component for symlinks going out of root.
      std::string real_path(root_);
      real_path.append(path.data(), path.size());
      struct stat st;
      if (::stat(real_path.c_str(), &st))
        return ErrorHandler::basicResponse(request, response, kStatusNotFound);
      if (S_ISREG(st.st_mode))
        return streamFile(request, response, real_path, st);
      else if (S_ISDIR(st.st_mode) && can_readdir_)
        return readDir(request, response, real_path);
      return ErrorHandler::basicResponse(request, response, kStatusForbidden);
    }
The documentation for this class was generated from the following files:
mimosa/http/fs-handler.hh
mimosa/http/fs-handler.cc