mimosa: mimosa::string::StringRef Class Reference
mimosa::string::StringRef Class Reference
#include <string-ref.hh>
Public Member Functions
StringRef ()
StringRef (const char *string)
StringRef (const char *string, size_t len)
StringRef (const char *string, const char *end)
StringRef (const std::string &str)
size_t size () const
const char * data () const
char operator[] (size_t pos) const
bool operator== (const StringRef &other) const
size_t find (char c, size_t pos) const
bool streq (const StringRef &other) const
bool strcaseeq (const StringRef &other) const
StringRef substr (size_t start=0, size_t n=npos) const
Static Public Attributes
static const size_t npos = -1
Detailed Description
Definition at line 12 of file string-ref.hh.
Constructor & Destructor Documentation
mimosa::string::StringRef::StringRef () [inline]
Definition at line 17 of file string-ref.hh.
Referenced by substr().
: data_(0), len_(0) {}
mimosa::string::StringRef::StringRef (const char * string) [inline]
Definition at line 18 of file string-ref.hh.
: data_(string), len_(::strlen(string)) {}
mimosa::string::StringRef::StringRef (const char * string, size_t len) [inline]
Definition at line 19 of file string-ref.hh.
: data_(string), len_(len) {}
mimosa::string::StringRef::StringRef (const char * string, const char * end) [inline]
Definition at line 20 of file string-ref.hh.
: data_(string), len_(end - string) {}
mimosa::string::StringRef::StringRef (const std::string & str) [inline]
Definition at line 21 of file string-ref.hh.
: data_(str.data()), len_(str.size()) {}
Member Function Documentation
const char* mimosa::string::StringRef::data () const [inline]
Definition at line 24 of file string-ref.hh.
{ return data_; }
size_t mimosa::string::StringRef::find (char c, size_t pos) const [inline]
Definition at line 32 of file string-ref.hh.
References npos.
Referenced by mimosa::http::FsHandler::handle().
{
        if (pos >= len_)
          return npos;
        const char * found = static_cast<const char *>(::memchr(data_ + pos, c, len_ - pos));
        return found ? found - data_ : npos;
      }
bool mimosa::string::StringRef::operator== (const StringRef & other) const [inline]
Definition at line 28 of file string-ref.hh.
References streq().
{
        return streq(other);
      }
char mimosa::string::StringRef::operator[] (size_t pos) const [inline]
Definition at line 26 of file string-ref.hh.
{ assert(len_ > pos); return data_[pos]; }
size_t mimosa::string::StringRef::size () const [inline]
Definition at line 23 of file string-ref.hh.
{ return len_; }
bool mimosa::string::StringRef::strcaseeq (const StringRef & other) const [inline]
Definition at line 42 of file string-ref.hh.
{
        return other.len_ == len_ && (other.data_ == data_ || !::strncasecmp(other.data_, data_, len_));
      }
bool mimosa::string::StringRef::streq (const StringRef & other) const [inline]
Definition at line 39 of file string-ref.hh.
Referenced by operator==().
{
        return other.len_ == len_ && (other.data_ == data_ || !::strncmp(other.data_, data_, len_));
      }
StringRef mimosa::string::StringRef::substr (size_t start = 0, size_t n = npos) const [inline]
Definition at line 46 of file string-ref.hh.
References npos, and StringRef().
{
        if (start >= len_)
          return StringRef();
        if (n == npos || start + n >= len_)
          n = len_ - start;
        return StringRef(data_ + start, n);
      }
Field Documentation
const size_t mimosa::string::StringRef::npos = -1 [static]
Definition at line 15 of file string-ref.hh.
Referenced by find(), mimosa::http::FsHandler::handle(), and substr().
The documentation for this class was generated from the following file:
mimosa/string/string-ref.hh