mimosa: mimosa::rpc::samples::pb::KeyValue Class Reference
mimosa::rpc::samples::pb::KeyValue Class Reference
#include <kv-db.pb.h>
Public Member Functions
KeyValue ()
virtual ~KeyValue ()
KeyValue (const KeyValue &from)
KeyValue & operator= (const KeyValue &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (KeyValue *other)
KeyValue * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const KeyValue &from)
void MergeFrom (const KeyValue &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_key () const
void clear_key ()
const ::std::string & key () const
void set_key (const ::std::string &value)
void set_key (const char *value)
void set_key (const void *value, size_t size)
inline::std::string * mutable_key ()
inline::std::string * release_key ()
bool has_value () const
void clear_value ()
const ::std::string & value () const
void set_value (const ::std::string &value)
void set_value (const char *value)
void set_value (const void *value, size_t size)
inline::std::string * mutable_value ()
inline::std::string * release_value ()
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const KeyValue & default_instance ()
Static Public Attributes
static const int kKeyFieldNumber = 1
static const int kValueFieldNumber = 2
Friends
void protobuf_AddDesc_kv_2ddb_2eproto ()
void protobuf_AssignDesc_kv_2ddb_2eproto ()
void protobuf_ShutdownFile_kv_2ddb_2eproto ()
Detailed Description
Definition at line 153 of file kv-db.pb.h.
Constructor & Destructor Documentation
mimosa::rpc::samples::pb::KeyValue::KeyValue ()
Definition at line 397 of file kv-db.pb.cc.
Referenced by New().
  : ::google::protobuf::Message() {
  SharedCtor();
}
mimosa::rpc::samples::pb::KeyValue::~KeyValue () [virtual]
Definition at line 418 of file kv-db.pb.cc.
                    {
  SharedDtor();
}
mimosa::rpc::samples::pb::KeyValue::KeyValue (const KeyValue & from)
Definition at line 405 of file kv-db.pb.cc.
References MergeFrom().
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}
Member Function Documentation
int mimosa::rpc::samples::pb::KeyValue::ByteSize () const
Definition at line 562 of file kv-db.pb.cc.
References has_key(), has_value(), key(), unknown_fields(), and value().
{
  int total_size = 0;
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes key = 1;
    if (has_key()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->key());
    }
    // required bytes value = 2;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->value());
    }
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}
void mimosa::rpc::samples::pb::KeyValue::Clear ()
Definition at line 453 of file kv-db.pb.cc.
References has_key(), has_value(), and mutable_unknown_fields().
Referenced by CopyFrom().
                     {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_key()) {
      if (key_ != &::google::protobuf::internal::kEmptyString) {
        key_->clear();
      }
    }
    if (has_value()) {
      if (value_ != &::google::protobuf::internal::kEmptyString) {
        value_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}
void mimosa::rpc::samples::pb::KeyValue::clear_key () [inline]
Definition at line 426 of file kv-db.pb.h.
{
  if (key_ != &::google::protobuf::internal::kEmptyString) {
    key_->clear();
  }
  clear_has_key();
}
void mimosa::rpc::samples::pb::KeyValue::clear_value () [inline]
Definition at line 484 of file kv-db.pb.h.
{
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    value_->clear();
  }
  clear_has_value();
}
void mimosa::rpc::samples::pb::KeyValue::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 617 of file kv-db.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
{
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}
void mimosa::rpc::samples::pb::KeyValue::CopyFrom (const KeyValue & from)
Definition at line 623 of file kv-db.pb.cc.
References Clear(), and MergeFrom().
{
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}
const KeyValue & mimosa::rpc::samples::pb::KeyValue::default_instance () [static]
Definition at line 443 of file kv-db.pb.cc.
References protobuf_AddDesc_kv_2ddb_2eproto.
{
  if (default_instance_ == NULL) protobuf_AddDesc_kv_2ddb_2eproto();  return *default_instance_;
}
const ::google::protobuf::Descriptor * mimosa::rpc::samples::pb::KeyValue::descriptor () [static]
Definition at line 438 of file kv-db.pb.cc.
{
  protobuf_AssignDescriptorsOnce();
  return KeyValue_descriptor_;
}
int mimosa::rpc::samples::pb::KeyValue::GetCachedSize () const [inline]
Definition at line 194 of file kv-db.pb.h.
{ return _cached_size_; }
google::protobuf::Metadata mimosa::rpc::samples::pb::KeyValue::GetMetadata () const
Definition at line 645 of file kv-db.pb.cc.
{
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = KeyValue_descriptor_;
  metadata.reflection = KeyValue_reflection_;
  return metadata;
}
bool mimosa::rpc::samples::pb::KeyValue::has_key () const [inline]
Definition at line 417 of file kv-db.pb.h.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
  return (_has_bits_[0] & 0x00000001u) != 0;
}
bool mimosa::rpc::samples::pb::KeyValue::has_value () const [inline]
Definition at line 475 of file kv-db.pb.h.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
  return (_has_bits_[0] & 0x00000002u) != 0;
}
bool mimosa::rpc::samples::pb::KeyValue::IsInitialized () const
Definition at line 629 of file kv-db.pb.cc.
{
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}
const ::std::string & mimosa::rpc::samples::pb::KeyValue::key () const [inline]
Definition at line 432 of file kv-db.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
  return *key_;
}
void mimosa::rpc::samples::pb::KeyValue::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 592 of file kv-db.pb.cc.
Referenced by CopyFrom(), and KeyValue().
{
  GOOGLE_CHECK_NE(&from, this);
  const KeyValue* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const KeyValue*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}
void mimosa::rpc::samples::pb::KeyValue::MergeFrom (const KeyValue & from)
Definition at line 604 of file kv-db.pb.cc.
References has_key(), has_value(), key(), mutable_unknown_fields(), set_key(), set_value(), unknown_fields(), and value().
{
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_key()) {
      set_key(from.key());
    }
    if (from.has_value()) {
      set_value(from.value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}
bool mimosa::rpc::samples::pb::KeyValue::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 470 of file kv-db.pb.cc.
References DO_, mutable_key(), mutable_unknown_fields(), and mutable_value().
{
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes key = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_key()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_value;
        break;
      }
      // required bytes value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_value()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}
std::string * mimosa::rpc::samples::pb::KeyValue::mutable_key () [inline]
Definition at line 456 of file kv-db.pb.h.
Referenced by MergePartialFromCodedStream().
{
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  return key_;
}
inline ::google::protobuf::UnknownFieldSet* mimosa::rpc::samples::pb::KeyValue::mutable_unknown_fields () [inline]
Definition at line 169 of file kv-db.pb.h.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
{
    return &_unknown_fields_;
  }
std::string * mimosa::rpc::samples::pb::KeyValue::mutable_value () [inline]
Definition at line 514 of file kv-db.pb.h.
Referenced by MergePartialFromCodedStream().
{
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  return value_;
}
KeyValue * mimosa::rpc::samples::pb::KeyValue::New () const
Definition at line 449 of file kv-db.pb.cc.
References KeyValue().
{
  return new KeyValue;
}
KeyValue& mimosa::rpc::samples::pb::KeyValue::operator= (const KeyValue & from) [inline]
Definition at line 160 of file kv-db.pb.h.
References CopyFrom().
{
    CopyFrom(from);
    return *this;
  }
std::string * mimosa::rpc::samples::pb::KeyValue::release_key () [inline]
Definition at line 463 of file kv-db.pb.h.
{
  clear_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = key_;
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
std::string * mimosa::rpc::samples::pb::KeyValue::release_value () [inline]
Definition at line 521 of file kv-db.pb.h.
{
  clear_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = value_;
    value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
void mimosa::rpc::samples::pb::KeyValue::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 519 of file kv-db.pb.cc.
References has_key(), has_value(), key(), unknown_fields(), and value().
{
  // required bytes key = 1;
  if (has_key()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->key(), output);
  }
  // required bytes value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->value(), output);
  }
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}
google::protobuf::uint8 * mimosa::rpc::samples::pb::KeyValue::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 539 of file kv-db.pb.cc.
References has_key(), has_value(), key(), unknown_fields(), and value().
{
  // required bytes key = 1;
  if (has_key()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->key(), target);
  }
  // required bytes value = 2;
  if (has_value()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->value(), target);
  }
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}
void mimosa::rpc::samples::pb::KeyValue::set_key (const ::std::string & value) [inline]
Definition at line 435 of file kv-db.pb.h.
Referenced by MergeFrom().
{
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
void mimosa::rpc::samples::pb::KeyValue::set_key (const char * value) [inline]
Definition at line 442 of file kv-db.pb.h.
{
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
void mimosa::rpc::samples::pb::KeyValue::set_key (const void * value, size_t size) [inline]
Definition at line 449 of file kv-db.pb.h.
{
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(reinterpret_cast<const char*>(value), size);
}
void mimosa::rpc::samples::pb::KeyValue::set_value (const ::std::string & value) [inline]
Definition at line 493 of file kv-db.pb.h.
Referenced by MergeFrom().
{
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
void mimosa::rpc::samples::pb::KeyValue::set_value (const char * value) [inline]
Definition at line 500 of file kv-db.pb.h.
{
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
void mimosa::rpc::samples::pb::KeyValue::set_value (const void * value, size_t size) [inline]
Definition at line 507 of file kv-db.pb.h.
{
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(reinterpret_cast<const char*>(value), size);
}
void mimosa::rpc::samples::pb::KeyValue::Swap (KeyValue * other)
Definition at line 635 of file kv-db.pb.cc.
{
  if (other != this) {
    std::swap(key_, other->key_);
    std::swap(value_, other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}
const ::google::protobuf::UnknownFieldSet& mimosa::rpc::samples::pb::KeyValue::unknown_fields () const [inline]
Definition at line 165 of file kv-db.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
    return _unknown_fields_;
  }
const ::std::string & mimosa::rpc::samples::pb::KeyValue::value () const [inline]
Definition at line 490 of file kv-db.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
  return *value_;
}
Friends And Related Function Documentation
void protobuf_AddDesc_kv_2ddb_2eproto () [friend]
Definition at line 122 of file kv-db.pb.cc.
Referenced by default_instance().
{
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013kv-db.proto\022\025mimosa.rpc.samples.pb\"\022\n\003"
    "Key\022\013\n\003key\030\001 \002(\014\"&\n\010KeyValue\022\013\n\003key\030\001 \002("
    "\014\022\r\n\005value\030\002 \002(\014\"F\n\006Result\022-\n\006status\030\001 \002"
    "(\0162\035.mimosa.rpc.samples.pb.Status\022\r\n\005val"
    "ue\030\002 \001(\014*4\n\006Status\022\007\n\003kOk\020\000\022\r\n\tkNotFound"
    "\020\001\022\022\n\016kInternalError\020\0022\325\001\n\010Database\022@\n\003g"
    "et\022\032.mimosa.rpc.samples.pb.Key\032\035.mimosa."
    "rpc.samples.pb.Result\022E\n\003set\022\037.mimosa.rp"
    "c.samples.pb.KeyValue\032\035.mimosa.rpc.sampl"
    "es.pb.Result\022@\n\003del\022\032.mimosa.rpc.samples"
    ".pb.Key\032\035.mimosa.rpc.samples.pb.Result", 438);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "kv-db.proto", &protobuf_RegisterTypes);
  Key::default_instance_ = new Key();
  KeyValue::default_instance_ = new KeyValue();
  Result::default_instance_ = new Result();
  Key::default_instance_->InitAsDefaultInstance();
  KeyValue::default_instance_->InitAsDefaultInstance();
  Result::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_kv_2ddb_2eproto);
}
void protobuf_AssignDesc_kv_2ddb_2eproto () [friend]
Definition at line 37 of file kv-db.pb.cc.
{
  protobuf_AddDesc_kv_2ddb_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "kv-db.proto");
  GOOGLE_CHECK(file != NULL);
  Key_descriptor_ = file->message_type(0);
  static const int Key_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Key, key_),
  };
  Key_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Key_descriptor_,
      Key::default_instance_,
      Key_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Key, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Key, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Key));
  KeyValue_descriptor_ = file->message_type(1);
  static const int KeyValue_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyValue, key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyValue, value_),
  };
  KeyValue_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      KeyValue_descriptor_,
      KeyValue::default_instance_,
      KeyValue_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyValue, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyValue, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(KeyValue));
  Result_descriptor_ = file->message_type(2);
  static const int Result_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Result, status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Result, value_),
  };
  Result_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Result_descriptor_,
      Result::default_instance_,
      Result_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Result, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Result, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Result));
  Status_descriptor_ = file->enum_type(0);
}
void protobuf_ShutdownFile_kv_2ddb_2eproto () [friend]
Definition at line 113 of file kv-db.pb.cc.
{
  delete Key::default_instance_;
  delete Key_reflection_;
  delete KeyValue::default_instance_;
  delete KeyValue_reflection_;
  delete Result::default_instance_;
  delete Result_reflection_;
}
Field Documentation
const int mimosa::rpc::samples::pb::KeyValue::kKeyFieldNumber = 1 [static]
Definition at line 210 of file kv-db.pb.h.
const int mimosa::rpc::samples::pb::KeyValue::kValueFieldNumber = 2 [static]
Definition at line 221 of file kv-db.pb.h.
The documentation for this class was generated from the following files:
mimosa/rpc/samples/kv-db.pb.h
mimosa/rpc/samples/kv-db.pb.cc