mimosa: mimosa::rpc::samples::pb::Result Class Reference
mimosa::rpc::samples::pb::Result Class Reference
#include <kv-db.pb.h>
Public Member Functions
Result ()
virtual ~Result ()
Result (const Result &from)
Result & operator= (const Result &from)
const
::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Result *other)
Result * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const Result &from)
void MergeFrom (const Result &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_status () const
void clear_status ()
mimosa::rpc::samples::pb::Status status () const
void set_status (mimosa::rpc::samples::pb::Status value)
bool has_value () const
void clear_value ()
const ::std::string & value () const
void set_value (const ::std::string &value)
void set_value (const char *value)
void set_value (const void *value, size_t size)
inline::std::string * mutable_value ()
inline::std::string * release_value ()
Static Public Member Functions
static const
::google::protobuf::Descriptor * descriptor ()
static const Result & default_instance ()
Static Public Attributes
static const int kStatusFieldNumber = 1
static const int kValueFieldNumber = 2
Friends
void protobuf_AddDesc_kv_2ddb_2eproto ()
void protobuf_AssignDesc_kv_2ddb_2eproto ()
void protobuf_ShutdownFile_kv_2ddb_2eproto ()
Detailed Description
Definition at line 253 of file kv-db.pb.h.
Constructor & Destructor Documentation
mimosa::rpc::samples::pb::Result::Result ()
Definition at line 661 of file kv-db.pb.cc.
Referenced by New().
  : ::google::protobuf::Message() {
  SharedCtor();
}
mimosa::rpc::samples::pb::Result::~Result () [virtual]
Definition at line 682 of file kv-db.pb.cc.
                {
  SharedDtor();
}
mimosa::rpc::samples::pb::Result::Result (const Result & from)
Definition at line 669 of file kv-db.pb.cc.
References MergeFrom().
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}
Member Function Documentation
int mimosa::rpc::samples::pb::Result::ByteSize () const
Definition at line 825 of file kv-db.pb.cc.
References has_status(), has_value(), status(), unknown_fields(), and value().
{
  int total_size = 0;
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .mimosa.rpc.samples.pb.Status status = 1;
    if (has_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->status());
    }
    // optional bytes value = 2;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->value());
    }
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}
void mimosa::rpc::samples::pb::Result::Clear ()
Definition at line 714 of file kv-db.pb.cc.
References has_value(), and mutable_unknown_fields().
Referenced by CopyFrom().
                   {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    status_ = 0;
    if (has_value()) {
      if (value_ != &::google::protobuf::internal::kEmptyString) {
        value_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}
void mimosa::rpc::samples::pb::Result::clear_status () [inline]
Definition at line 546 of file kv-db.pb.h.
{
  status_ = 0;
  clear_has_status();
}
void mimosa::rpc::samples::pb::Result::clear_value () [inline]
Definition at line 569 of file kv-db.pb.h.
{
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    value_->clear();
  }
  clear_has_value();
}
void mimosa::rpc::samples::pb::Result::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 879 of file kv-db.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=().
{
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}
void mimosa::rpc::samples::pb::Result::CopyFrom (const Result & from)
Definition at line 885 of file kv-db.pb.cc.
References Clear(), and MergeFrom().
{
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}
const Result & mimosa::rpc::samples::pb::Result::default_instance () [static]
Definition at line 704 of file kv-db.pb.cc.
References protobuf_AddDesc_kv_2ddb_2eproto.
{
  if (default_instance_ == NULL) protobuf_AddDesc_kv_2ddb_2eproto();  return *default_instance_;
}
const ::google::protobuf::Descriptor * mimosa::rpc::samples::pb::Result::descriptor () [static]
Definition at line 699 of file kv-db.pb.cc.
{
  protobuf_AssignDescriptorsOnce();
  return Result_descriptor_;
}
int mimosa::rpc::samples::pb::Result::GetCachedSize () const [inline]
Definition at line 294 of file kv-db.pb.h.
{ return _cached_size_; }
google::protobuf::Metadata mimosa::rpc::samples::pb::Result::GetMetadata () const
Definition at line 907 of file kv-db.pb.cc.
{
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Result_descriptor_;
  metadata.reflection = Result_reflection_;
  return metadata;
}
bool mimosa::rpc::samples::pb::Result::has_status () const [inline]
Definition at line 537 of file kv-db.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
  return (_has_bits_[0] & 0x00000001u) != 0;
}
bool mimosa::rpc::samples::pb::Result::has_value () const [inline]
Definition at line 560 of file kv-db.pb.h.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
  return (_has_bits_[0] & 0x00000002u) != 0;
}
bool mimosa::rpc::samples::pb::Result::IsInitialized () const
Definition at line 891 of file kv-db.pb.cc.
{
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}
void mimosa::rpc::samples::pb::Result::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 854 of file kv-db.pb.cc.
Referenced by CopyFrom(), and Result().
{
  GOOGLE_CHECK_NE(&from, this);
  const Result* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Result*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}
void mimosa::rpc::samples::pb::Result::MergeFrom (const Result & from)
Definition at line 866 of file kv-db.pb.cc.
References has_status(), has_value(), mutable_unknown_fields(), set_status(), set_value(), status(), unknown_fields(), and value().
{
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_status()) {
      set_status(from.status());
    }
    if (from.has_value()) {
      set_value(from.value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}
bool mimosa::rpc::samples::pb::Result::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 727 of file kv-db.pb.cc.
References DO_, mutable_unknown_fields(), mutable_value(), set_status(), mimosa::rpc::samples::pb::Status_IsValid(), and value().
{
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .mimosa.rpc.samples.pb.Status status = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (mimosa::rpc::samples::pb::Status_IsValid(value)) {
            set_status(static_cast< mimosa::rpc::samples::pb::Status >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_value;
        break;
      }
      // optional bytes value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_value()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}
inline ::google::protobuf::UnknownFieldSet* mimosa::rpc::samples::pb::Result::mutable_unknown_fields () [inline]
Definition at line 269 of file kv-db.pb.h.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
{
    return &_unknown_fields_;
  }
std::string * mimosa::rpc::samples::pb::Result::mutable_value () [inline]
Definition at line 599 of file kv-db.pb.h.
Referenced by MergePartialFromCodedStream().
{
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  return value_;
}
Result * mimosa::rpc::samples::pb::Result::New () const
Definition at line 710 of file kv-db.pb.cc.
References Result().
{
  return new Result;
}
Result& mimosa::rpc::samples::pb::Result::operator= (const Result & from) [inline]
Definition at line 260 of file kv-db.pb.h.
References CopyFrom().
{
    CopyFrom(from);
    return *this;
  }
std::string * mimosa::rpc::samples::pb::Result::release_value () [inline]
Definition at line 606 of file kv-db.pb.h.
{
  clear_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = value_;
    value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
void mimosa::rpc::samples::pb::Result::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 783 of file kv-db.pb.cc.
References has_status(), has_value(), status(), unknown_fields(), and value().
{
  // required .mimosa.rpc.samples.pb.Status status = 1;
  if (has_status()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->status(), output);
  }
  // optional bytes value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->value(), output);
  }
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}
google::protobuf::uint8 * mimosa::rpc::samples::pb::Result::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 803 of file kv-db.pb.cc.
References has_status(), has_value(), status(), unknown_fields(), and value().
{
  // required .mimosa.rpc.samples.pb.Status status = 1;
  if (has_status()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->status(), target);
  }
  // optional bytes value = 2;
  if (has_value()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->value(), target);
  }
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}
void mimosa::rpc::samples::pb::Result::set_status (mimosa::rpc::samples::pb::Status value) [inline]
Definition at line 553 of file kv-db.pb.h.
References mimosa::rpc::samples::pb::Status_IsValid(), and value().
Referenced by MergeFrom(), and MergePartialFromCodedStream().
{
  GOOGLE_DCHECK(mimosa::rpc::samples::pb::Status_IsValid(value));
  set_has_status();
  status_ = value;
}
void mimosa::rpc::samples::pb::Result::set_value (const ::std::string & value) [inline]
Definition at line 578 of file kv-db.pb.h.
Referenced by MergeFrom().
{
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
void mimosa::rpc::samples::pb::Result::set_value (const char * value) [inline]
Definition at line 585 of file kv-db.pb.h.
{
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
void mimosa::rpc::samples::pb::Result::set_value (const void * value, size_t size) [inline]
Definition at line 592 of file kv-db.pb.h.
{
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(reinterpret_cast<const char*>(value), size);
}
mimosa::rpc::samples::pb::Status mimosa::rpc::samples::pb::Result::status () const [inline]
Definition at line 550 of file kv-db.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
  return static_cast< mimosa::rpc::samples::pb::Status >(status_);
}
void mimosa::rpc::samples::pb::Result::Swap (Result * other)
Definition at line 897 of file kv-db.pb.cc.
{
  if (other != this) {
    std::swap(status_, other->status_);
    std::swap(value_, other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}
const ::google::protobuf::UnknownFieldSet& mimosa::rpc::samples::pb::Result::unknown_fields () const [inline]
Definition at line 265 of file kv-db.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
{
    return _unknown_fields_;
  }
const ::std::string & mimosa::rpc::samples::pb::Result::value () const [inline]
Definition at line 575 of file kv-db.pb.h.
Referenced by ByteSize(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_status().
{
  return *value_;
}
Friends And Related Function Documentation
void protobuf_AddDesc_kv_2ddb_2eproto () [friend]
Definition at line 122 of file kv-db.pb.cc.
Referenced by default_instance().
{
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013kv-db.proto\022\025mimosa.rpc.samples.pb\"\022\n\003"
    "Key\022\013\n\003key\030\001 \002(\014\"&\n\010KeyValue\022\013\n\003key\030\001 \002("
    "\014\022\r\n\005value\030\002 \002(\014\"F\n\006Result\022-\n\006status\030\001 \002"
    "(\0162\035.mimosa.rpc.samples.pb.Status\022\r\n\005val"
    "ue\030\002 \001(\014*4\n\006Status\022\007\n\003kOk\020\000\022\r\n\tkNotFound"
    "\020\001\022\022\n\016kInternalError\020\0022\325\001\n\010Database\022@\n\003g"
    "et\022\032.mimosa.rpc.samples.pb.Key\032\035.mimosa."
    "rpc.samples.pb.Result\022E\n\003set\022\037.mimosa.rp"
    "c.samples.pb.KeyValue\032\035.mimosa.rpc.sampl"
    "es.pb.Result\022@\n\003del\022\032.mimosa.rpc.samples"
    ".pb.Key\032\035.mimosa.rpc.samples.pb.Result", 438);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "kv-db.proto", &protobuf_RegisterTypes);
  Key::default_instance_ = new Key();
  KeyValue::default_instance_ = new KeyValue();
  Result::default_instance_ = new Result();
  Key::default_instance_->InitAsDefaultInstance();
  KeyValue::default_instance_->InitAsDefaultInstance();
  Result::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_kv_2ddb_2eproto);
}
void protobuf_AssignDesc_kv_2ddb_2eproto () [friend]
Definition at line 37 of file kv-db.pb.cc.
{
  protobuf_AddDesc_kv_2ddb_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "kv-db.proto");
  GOOGLE_CHECK(file != NULL);
  Key_descriptor_ = file->message_type(0);
  static const int Key_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Key, key_),
  };
  Key_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Key_descriptor_,
      Key::default_instance_,
      Key_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Key, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Key, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Key));
  KeyValue_descriptor_ = file->message_type(1);
  static const int KeyValue_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyValue, key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyValue, value_),
  };
  KeyValue_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      KeyValue_descriptor_,
      KeyValue::default_instance_,
      KeyValue_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyValue, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyValue, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(KeyValue));
  Result_descriptor_ = file->message_type(2);
  static const int Result_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Result, status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Result, value_),
  };
  Result_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Result_descriptor_,
      Result::default_instance_,
      Result_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Result, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Result, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Result));
  Status_descriptor_ = file->enum_type(0);
}
void protobuf_ShutdownFile_kv_2ddb_2eproto () [friend]
Definition at line 113 of file kv-db.pb.cc.
{
  delete Key::default_instance_;
  delete Key_reflection_;
  delete KeyValue::default_instance_;
  delete KeyValue_reflection_;
  delete Result::default_instance_;
  delete Result_reflection_;
}
Field Documentation
const int mimosa::rpc::samples::pb::Result::kStatusFieldNumber = 1 [static]
Definition at line 310 of file kv-db.pb.h.
const int mimosa::rpc::samples::pb::Result::kValueFieldNumber = 2 [static]
Definition at line 317 of file kv-db.pb.h.
The documentation for this class was generated from the following files:
mimosa/rpc/samples/kv-db.pb.h
mimosa/rpc/samples/kv-db.pb.cc