mimosa: mimosa::rpc::samples::pb::Database_Server Class Reference
mimosa::rpc::samples::pb::Database_Server Class Reference
#include <kv-db.pb.h>
Public Member Functions
MIMOSA_DEF_PTR (Database_Server)
virtual void get (::mimosa::rpc::Call< ::mimosa::rpc::samples::pb::Key,::mimosa::rpc::samples::pb::Result >::Ptr call)=0
virtual void set (::mimosa::rpc::Call< ::mimosa::rpc::samples::pb::KeyValue,::mimosa::rpc::samples::pb::Result >::Ptr call)=0
virtual void del (::mimosa::rpc::Call< ::mimosa::rpc::samples::pb::Key,::mimosa::rpc::samples::pb::Result >::Ptr call)=0
Protected Member Functions
virtual
::mimosa::rpc::Service::CallMethodStatus callMethod (::mimosa::rpc::BasicCall::Ptr basic_call, const char *request_data, uint32_t request_size)
Detailed Description
Definition at line 630 of file kv-db.pb.h.
Member Function Documentation
virtual ::mimosa::rpc::Service::CallMethodStatus mimosa::rpc::samples::pb::Database_Server::callMethod (::mimosa::rpc::BasicCall::Ptr basic_call, const char * request_data, uint32_t request_size) [inline, protected]
Definition at line 650 of file kv-db.pb.h.
References del(), mimosa::RefCountedPtr< T >::get(), mimosa::rpc::kInvalidMsg, mimosa::rpc::Service::kMethodNotFound, and mimosa::rpc::Service::kSucceed.
  {
    switch (basic_call->methodId())
    {
    case 4248514160UL: // get()
    {
      ::mimosa::rpc::Call< ::mimosa::rpc::samples::pb::Key,
                           ::mimosa::rpc::samples::pb::Result>::Ptr call(
        reinterpret_cast< ::mimosa::rpc::Call< ::mimosa::rpc::samples::pb::Key,
                                               ::mimosa::rpc::samples::pb::Result> *> (basic_call.get()));
      call->allocateMessages();
      if (!call->request().ParseFromArray(request_data, request_size))
        return ::mimosa::rpc::Service::kInvalidMsg;
      get(call);
      return ::mimosa::rpc::Service::kSucceed;
    }
    case 3860080092UL: // set()
    {
      ::mimosa::rpc::Call< ::mimosa::rpc::samples::pb::KeyValue,
                           ::mimosa::rpc::samples::pb::Result>::Ptr call(
        reinterpret_cast< ::mimosa::rpc::Call< ::mimosa::rpc::samples::pb::KeyValue,
                                               ::mimosa::rpc::samples::pb::Result> *> (basic_call.get()));
      call->allocateMessages();
      if (!call->request().ParseFromArray(request_data, request_size))
        return ::mimosa::rpc::Service::kInvalidMsg;
      set(call);
      return ::mimosa::rpc::Service::kSucceed;
    }
    case 3960539263UL: // del()
    {
      ::mimosa::rpc::Call< ::mimosa::rpc::samples::pb::Key,
                           ::mimosa::rpc::samples::pb::Result>::Ptr call(
        reinterpret_cast< ::mimosa::rpc::Call< ::mimosa::rpc::samples::pb::Key,
                                               ::mimosa::rpc::samples::pb::Result> *> (basic_call.get()));
      call->allocateMessages();
      if (!call->request().ParseFromArray(request_data, request_size))
        return ::mimosa::rpc::Service::kInvalidMsg;
      del(call);
      return ::mimosa::rpc::Service::kSucceed;
    }
    default:
      return ::mimosa::rpc::Service::kMethodNotFound;
    }
  }
virtual void mimosa::rpc::samples::pb::Database_Server::del (::mimosa::rpc::Call< ::mimosa::rpc::samples::pb::Key,::mimosa::rpc::samples::pb::Result >::Ptr call) [pure virtual]
Referenced by callMethod().
virtual void mimosa::rpc::samples::pb::Database_Server::get (::mimosa::rpc::Call< ::mimosa::rpc::samples::pb::Key,::mimosa::rpc::samples::pb::Result >::Ptr call) [pure virtual]
mimosa::rpc::samples::pb::Database_Server::MIMOSA_DEF_PTR (Database_Server)
virtual void mimosa::rpc::samples::pb::Database_Server::set (::mimosa::rpc::Call< ::mimosa::rpc::samples::pb::KeyValue,::mimosa::rpc::samples::pb::Result >::Ptr call) [pure virtual]
The documentation for this class was generated from the following file:
mimosa/rpc/samples/kv-db.pb.h