mimosa: mimosa::RefCountedPtr< T > Class Template Reference
mimosa::RefCountedPtr< T > Class Template Reference
#include <ref-counted-ptr.hh>
Public Member Functions
RefCountedPtr ()
RefCountedPtr (T *ptr)
RefCountedPtr (const RefCountedPtr< T > &ptr)
template<typename U >
RefCountedPtr (const RefCountedPtr< U > &ptr)
~RefCountedPtr ()
RefCountedPtr< T > & operator= (T *ptr)
RefCountedPtr< T > & operator= (const RefCountedPtr< T > &ptr)
bool operator! () const
operator bool () const
T & operator* () const
T * operator-> () const
template<typename Member >
auto operator->* (Member member) const -> decltype(((T *) nullptr)-> *member)
T * get () const
void assign (T *ptr)
void clear ()
Detailed Description
template<typename T>
class mimosa::RefCountedPtr< T >
Definition at line 7 of file ref-counted-ptr.hh.
Constructor & Destructor Documentation
template<typename T> mimosa::RefCountedPtr< T >::RefCountedPtr () [inline]
Definition at line 10 of file ref-counted-ptr.hh.
      : ptr_(nullptr)
    {
    }
template<typename T> mimosa::RefCountedPtr< T >::RefCountedPtr (T * ptr) [inline]
Definition at line 15 of file ref-counted-ptr.hh.
References mimosa::addRef().
      : ptr_(ptr)
    {
      if (ptr_)
        addRef(ptr_);
    }
template<typename T> mimosa::RefCountedPtr< T >::RefCountedPtr (const RefCountedPtr< T > & ptr) [inline]
Definition at line 22 of file ref-counted-ptr.hh.
References mimosa::addRef().
      : ptr_(ptr.get())
    {
      if (ptr_)
        addRef(ptr_);
    }
template<typename T> template<typename U > mimosa::RefCountedPtr< T >::RefCountedPtr (const RefCountedPtr< U > & ptr) [inline]
Definition at line 30 of file ref-counted-ptr.hh.
References mimosa::addRef().
      : ptr_(ptr.get())
    {
      if (ptr_)
        addRef(ptr_);
    }
template<typename T> mimosa::RefCountedPtr< T >::~RefCountedPtr () [inline]
Definition at line 37 of file ref-counted-ptr.hh.
References mimosa::RefCountedPtr< T >::assign().
    {
      assign(nullptr);
    }
Member Function Documentation
template<typename T> void mimosa::RefCountedPtr< T >::assign (T * ptr) [inline]
Definition at line 69 of file ref-counted-ptr.hh.
References mimosa::addRef(), and mimosa::releaseRef().
Referenced by mimosa::RefCountedPtr< T >::clear(), mimosa::RefCountedPtr< T >::operator=(), and mimosa::RefCountedPtr< T >::~RefCountedPtr().
    {
      if (ptr)
        addRef(ptr);
      if (ptr_)
        releaseRef(ptr_);
      ptr_ = ptr;
    }
template<typename T> void mimosa::RefCountedPtr< T >::clear () [inline]
Definition at line 78 of file ref-counted-ptr.hh.
References mimosa::RefCountedPtr< T >::assign().
Referenced by mimosa::http::ServerChannel::run().
{ assign(nullptr); }
template<typename T> T* mimosa::RefCountedPtr< T >::get () const [inline]
Definition at line 68 of file ref-counted-ptr.hh.
Referenced by mimosa::rpc::samples::pb::Database_Server::callMethod(), and mimosa::RefCountedPtr< T >::operator=().
{ return ptr_; }
template<typename T> mimosa::RefCountedPtr< T >::operator bool () const [inline]
Definition at line 59 of file ref-counted-ptr.hh.
    {
      return ptr_;
    }
template<typename T> bool mimosa::RefCountedPtr< T >::operator! () const [inline]
Definition at line 54 of file ref-counted-ptr.hh.
    {
      return !ptr_;
    }
template<typename T> T& mimosa::RefCountedPtr< T >::operator* () const [inline]
Definition at line 64 of file ref-counted-ptr.hh.
{ return *ptr_; }
template<typename T> T* mimosa::RefCountedPtr< T >::operator-> () const [inline]
Definition at line 65 of file ref-counted-ptr.hh.
{ return ptr_; }
template<typename T> template<typename Member > auto mimosa::RefCountedPtr< T >::operator->* (Member member) const [inline]
Definition at line 67 of file ref-counted-ptr.hh.
{ return ptr_->*member; }
template<typename T> RefCountedPtr<T>& mimosa::RefCountedPtr< T >::operator= (T * ptr) [inline]
Definition at line 42 of file ref-counted-ptr.hh.
References mimosa::RefCountedPtr< T >::assign().
    {
      assign(ptr);
      return *this;
    }
template<typename T> RefCountedPtr<T>& mimosa::RefCountedPtr< T >::operator= (const RefCountedPtr< T > & ptr) [inline]
Definition at line 48 of file ref-counted-ptr.hh.
References mimosa::RefCountedPtr< T >::assign(), and mimosa::RefCountedPtr< T >::get().
    {
      assign(ptr.get());
      return *this;
    }
The documentation for this class was generated from the following file:
mimosa/ref-counted-ptr.hh