mimosa: mimosa::container::IntrusiveSlist< T, Ptr, Member > Class Template Reference
mimosa::container::IntrusiveSlist< T, Ptr, Member > Class Template Reference
#include <intrusive-slist.hh>
Public Types
typedef IntrusiveSlistIterator
< T, Ptr, Member > iterator
Public Member Functions
IntrusiveSlist ()
~IntrusiveSlist ()
bool empty () const
size_t size () const
void push (Ptr item)
Ptr front () const
Ptr back () const
void pop ()
void clear ()
iterator begin () const
iterator end () const
Friends
class IntrusiveSlistIterator< T, Ptr, Member >
Detailed Description
template<typename T, typename Ptr, IntrusiveSlistHook< Ptr > T::* Member>
class mimosa::container::IntrusiveSlist< T, Ptr, Member >
Definition at line 65 of file intrusive-slist.hh.
Member Typedef Documentation
template<typename T, typename Ptr, IntrusiveSlistHook< Ptr > T::* Member> typedef IntrusiveSlistIterator<T, Ptr, Member> mimosa::container::IntrusiveSlist< T, Ptr, Member >::iterator
Definition at line 68 of file intrusive-slist.hh.
Constructor & Destructor Documentation
template<typename T, typename Ptr, IntrusiveSlistHook< Ptr > T::* Member> mimosa::container::IntrusiveSlist< T, Ptr, Member >::IntrusiveSlist () [inline]
Definition at line 71 of file intrusive-slist.hh.
: tail_(nullptr), size_(0) {}
template<typename T, typename Ptr, IntrusiveSlistHook< Ptr > T::* Member> mimosa::container::IntrusiveSlist< T, Ptr, Member >::~IntrusiveSlist () [inline]
Definition at line 72 of file intrusive-slist.hh.
      {
        while (!empty())
          pop();
      }
Member Function Documentation
template<typename T, typename Ptr, IntrusiveSlistHook< Ptr > T::* Member> Ptr mimosa::container::IntrusiveSlist< T, Ptr, Member >::back () const [inline]
Definition at line 107 of file intrusive-slist.hh.
      {
        assert(tail_);
        return tail_;
      }
template<typename T, typename Ptr, IntrusiveSlistHook< Ptr > T::* Member> iterator mimosa::container::IntrusiveSlist< T, Ptr, Member >::begin () const [inline]
Definition at line 138 of file intrusive-slist.hh.
Referenced by mimosa::stream::BufferedStream::flush(), mimosa::http::ResponseWriter::flush(), mimosa::http::Response::toHttpHeader(), and mimosa::stream::BufferedStream::write().
{ return empty() ? end() : iterator(*this, (tail_->*Member).next_); }
template<typename T, typename Ptr, IntrusiveSlistHook< Ptr > T::* Member> void mimosa::container::IntrusiveSlist< T, Ptr, Member >::clear () [inline]
Definition at line 131 of file intrusive-slist.hh.
Referenced by mimosa::http::Response::clear(), mimosa::http::ResponseWriter::clear(), and mimosa::http::ResponseWriter::flush().
      {
        // poping everything to unlink (and potentially release while unref)
        while (!empty())
          pop();
      }
template<typename T, typename Ptr, IntrusiveSlistHook< Ptr > T::* Member> bool mimosa::container::IntrusiveSlist< T, Ptr, Member >::empty () const [inline]
Definition at line 78 of file intrusive-slist.hh.
Referenced by mimosa::container::IntrusiveSlist< Cookie, Cookie::Ptr,&Cookie::next_ >::begin(), mimosa::container::IntrusiveSlist< Cookie, Cookie::Ptr,&Cookie::next_ >::clear(), mimosa::stream::BufferedStream::flush(), and mimosa::container::IntrusiveSlist< Cookie, Cookie::Ptr,&Cookie::next_ >::~IntrusiveSlist().
      {
        return !tail_;
      }
template<typename T, typename Ptr, IntrusiveSlistHook< Ptr > T::* Member> iterator mimosa::container::IntrusiveSlist< T, Ptr, Member >::end () const [inline]
Definition at line 139 of file intrusive-slist.hh.
Referenced by mimosa::container::IntrusiveSlist< Cookie, Cookie::Ptr,&Cookie::next_ >::begin(), mimosa::stream::BufferedStream::flush(), mimosa::http::ResponseWriter::flush(), mimosa::http::Response::toHttpHeader(), and mimosa::stream::BufferedStream::write().
{ return iterator(*this, nullptr); }
template<typename T, typename Ptr, IntrusiveSlistHook< Ptr > T::* Member> Ptr mimosa::container::IntrusiveSlist< T, Ptr, Member >::front () const [inline]
Definition at line 101 of file intrusive-slist.hh.
      {
        assert(tail_);
        return (tail_->*Member).next_;
      }
template<typename T, typename Ptr, IntrusiveSlistHook< Ptr > T::* Member> void mimosa::container::IntrusiveSlist< T, Ptr, Member >::pop () [inline]
Definition at line 113 of file intrusive-slist.hh.
Referenced by mimosa::container::IntrusiveSlist< Cookie, Cookie::Ptr,&Cookie::next_ >::clear(), mimosa::stream::BufferedStream::flush(), mimosa::stream::BufferedStream::write(), and mimosa::container::IntrusiveSlist< Cookie, Cookie::Ptr,&Cookie::next_ >::~IntrusiveSlist().
      {
        if (!tail_)
          return;
        --size_;
        if (tail_ == (tail_->*Member).next_)
        {
          (tail_->*Member).next_ = nullptr;
          tail_ = nullptr;
        }
        else
        {
          Ptr tmp                = (tail_->*Member).next_;
          (tail_->*Member).next_ = (tmp->*Member).next_;
          (tmp->*Member).next_   = nullptr;
        }
      }
template<typename T, typename Ptr, IntrusiveSlistHook< Ptr > T::* Member> void mimosa::container::IntrusiveSlist< T, Ptr, Member >::push (Ptr item) [inline]
Definition at line 88 of file intrusive-slist.hh.
Referenced by mimosa::http::ResponseWriter::write().
      {
        ++size_;
        if (!tail_)
          (item->*Member).next_ = item;
        else
        {
          (item->*Member).next_  = (tail_->*Member).next_;
          (tail_->*Member).next_ = item;
        }
        tail_ = item;
      }
template<typename T, typename Ptr, IntrusiveSlistHook< Ptr > T::* Member> size_t mimosa::container::IntrusiveSlist< T, Ptr, Member >::size () const [inline]
Definition at line 83 of file intrusive-slist.hh.
Referenced by mimosa::stream::BufferedStream::flush(), and mimosa::stream::BufferedStream::write().
      {
        return size_;
      }
Friends And Related Function Documentation
template<typename T, typename Ptr, IntrusiveSlistHook< Ptr > T::* Member> friend class IntrusiveSlistIterator< T, Ptr, Member > [friend]
Definition at line 69 of file intrusive-slist.hh.
The documentation for this class was generated from the following file:
mimosa/container/intrusive-slist.hh