mimosa: mimosa::sync::Condition Class Reference
mimosa::sync::Condition Class Reference
#include <condition.hh>
Public Member Functions
Condition ()
~Condition ()
template<typename Mutex >
void wait (Mutex &mutex, runtime::Time time=0)
void wakeOne ()
void wakeAll ()
Detailed Description
Definition at line 15 of file condition.hh.
Constructor & Destructor Documentation
mimosa::sync::Condition::Condition () [inline]
Definition at line 18 of file condition.hh.
        : cond_(::melon_cond_new())
      {
        if (!cond_)
          throw std::bad_alloc();
      }
mimosa::sync::Condition::~Condition () [inline]
Definition at line 25 of file condition.hh.
{ ::melon_cond_destroy(cond_); }
Member Function Documentation
template<typename Mutex > void mimosa::sync::Condition::wait (Mutex & mutex, runtime::Time time = 0) [inline]
Definition at line 28 of file condition.hh.
References mimosa::runtime::time().
Referenced by mimosa::sync::Channel< stream::Buffer::Ptr, stream::Buffer::Slist >::pop(), and mimosa::rpc::BasicCall::wait().
      { ::melon_cond_timedwait(cond_, mutex.mutex_, time); }
void mimosa::sync::Condition::wakeAll () [inline]
Definition at line 32 of file condition.hh.
Referenced by mimosa::rpc::BasicCall::cancel(), mimosa::sync::Channel< stream::Buffer::Ptr, stream::Buffer::Slist >::close(), and mimosa::rpc::BasicCall::finished().
{ ::melon_cond_broadcast(cond_); }
void mimosa::sync::Condition::wakeOne () [inline]
Definition at line 31 of file condition.hh.
Referenced by mimosa::sync::Channel< stream::Buffer::Ptr, stream::Buffer::Slist >::push().
{ ::melon_cond_signal(cond_); }
The documentation for this class was generated from the following file:
mimosa/sync/condition.hh