mimosa: mimosa::http::ResponseWriter Class Reference
mimosa::http::ResponseWriter Class Reference
#include <response-writer.hh>
Public Member Functions
MIMOSA_DEF_PTR (ResponseWriter)
ResponseWriter (stream::Stream::Ptr stream)
~ResponseWriter ()
bool sendHeader (runtime::Time timeout)
void clear ()
virtual int64_t write (const char *data, uint64_t nbytes, runtime::Time timeout=0)
virtual int64_t read (char *data, uint64_t nbytes, runtime::Time timeout=0)
virtual bool flush (runtime::Time timeout)
Friends
class ServerChannel
Detailed Description
This stream buffers output until sendHeader is called. Then it writes directly to the underlying stream
Definition at line 16 of file response-writer.hh.
Constructor & Destructor Documentation
mimosa::http::ResponseWriter::ResponseWriter (stream::Stream::Ptr stream)
Definition at line 10 of file response-writer.cc.
      : stream_(stream),
        buffers_(),
        header_sent_(false)
    {
    }
mimosa::http::ResponseWriter::~ResponseWriter ()
Definition at line 17 of file response-writer.cc.
    {
    }
Member Function Documentation
void mimosa::http::ResponseWriter::clear ()
Reimplemented from mimosa::http::Response.
Definition at line 84 of file response-writer.cc.
References mimosa::container::IntrusiveSlist< T, Ptr, Member >::clear().
    {
      Response::clear();
      buffers_.clear();
      header_sent_ = false;
    }
bool mimosa::http::ResponseWriter::flush (runtime::Time timeout) [virtual]
does nothing until sendHeader(), then flushes the write buffer
Reimplemented from mimosa::stream::Stream.
Definition at line 49 of file response-writer.cc.
References mimosa::container::IntrusiveSlist< T, Ptr, Member >::begin(), mimosa::container::IntrusiveSlist< T, Ptr, Member >::clear(), and mimosa::container::IntrusiveSlist< T, Ptr, Member >::end().
    {
      for (auto it = buffers_.begin(); it != buffers_.end(); ++it)
      {
        auto ret = stream_->write(it->data(), it->size(), timeout);
        if (ret < 0)
          return false;
        assert(ret == it->size()); // because of underlying buffered stream
                                   // and lazy programmer ;-)
      }
      buffers_.clear();
      stream_->flush(timeout);
      return true;
    }
mimosa::http::ResponseWriter::MIMOSA_DEF_PTR (ResponseWriter)
int64_t mimosa::http::ResponseWriter::read (char * data, uint64_t nbytes, runtime::Time timeout = 0) [virtual]
Warning:
this should never be called, will abort
Implements mimosa::stream::Stream.
Definition at line 22 of file response-writer.cc.
    {
      assert(false && "read is an invalid operation on ResponseWriter");
      errno = EINVAL;
      return -1;
    }
bool mimosa::http::ResponseWriter::sendHeader (runtime::Time timeout)
Writes the header to the client. If content_length_ is 0 then the content length is unspecified and the connection will close after this response (keep_alive_ will be set to false). Until you call sendResponseHeader, everything you write to body is buffered, so when you finishes Response knows the amount of data to be written and set content_length_
Definition at line 74 of file response-writer.cc.
References mimosa::http::Response::toHttpHeader().
    {
      if (header_sent_)
        return true;
      header_sent_ = true;
      auto data = toHttpHeader();
      return stream_->write(data.data(), data.size(), timeout) == data.size();
    }
int64_t mimosa::http::ResponseWriter::write (const char * data, uint64_t nbytes, runtime::Time timeout = 0) [virtual]
Stream related stuff buffers the data until sendHeader()
Implements mimosa::stream::Stream.
Definition at line 30 of file response-writer.cc.
References mimosa::container::IntrusiveSlist< T, Ptr, Member >::push().
Referenced by mimosa::http::ErrorHandler::basicResponse().
    {
      if (header_sent_)
        return stream_->write(data, nbytes, timeout);
      stream::Buffer::Ptr buffer = new stream::Buffer(data, nbytes);
      buffers_.push(buffer);
      return nbytes;
    }
Friends And Related Function Documentation
friend class ServerChannel [friend]
Definition at line 47 of file response-writer.hh.
The documentation for this class was generated from the following files:
mimosa/http/response-writer.hh
mimosa/http/response-writer.cc