mimosa: mimosa::rpc::samples::pb Namespace Reference
mimosa::rpc::samples::pb Namespace Reference
Data Structures
struct StaticDescriptorInitializer_kv_2ddb_2eproto
class Key
class KeyValue
class Result
class Database
class Database_Server
class Database_Client
Enumerations
enum Status { kOk = 0, kNotFound = 1, kInternalError = 2 }
Functions
void protobuf_AssignDesc_kv_2ddb_2eproto ()
void protobuf_ShutdownFile_kv_2ddb_2eproto ()
void protobuf_AddDesc_kv_2ddb_2eproto ()
const
::google::protobuf::EnumDescriptor * Status_descriptor ()
bool Status_IsValid (int value)
const ::std::string & Status_Name (Status value)
bool Status_Parse (const ::std::string &name, Status *value)
Variables
struct
mimosa::rpc::samples::pb::StaticDescriptorInitializer_kv_2ddb_2eproto static_descriptor_initializer_kv_2ddb_2eproto_
const Status Status_MIN = kOk
const Status Status_MAX = kInternalError
const int Status_ARRAYSIZE = Status_MAX + 1
Enumeration Type Documentation
enum mimosa::rpc::samples::pb::Status
Enumerator:
kOk
kNotFound
kInternalError
Definition at line 45 of file kv-db.pb.h.
            {
  kOk = 0,
  kNotFound = 1,
  kInternalError = 2
};
Function Documentation
void mimosa::rpc::samples::pb::protobuf_AddDesc_kv_2ddb_2eproto ()
Definition at line 122 of file kv-db.pb.cc.
References protobuf_ShutdownFile_kv_2ddb_2eproto().
Referenced by protobuf_AssignDesc_kv_2ddb_2eproto(), and mimosa::rpc::samples::pb::StaticDescriptorInitializer_kv_2ddb_2eproto::StaticDescriptorInitializer_kv_2ddb_2eproto().
{
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013kv-db.proto\022\025mimosa.rpc.samples.pb\"\022\n\003"
    "Key\022\013\n\003key\030\001 \002(\014\"&\n\010KeyValue\022\013\n\003key\030\001 \002("
    "\014\022\r\n\005value\030\002 \002(\014\"F\n\006Result\022-\n\006status\030\001 \002"
    "(\0162\035.mimosa.rpc.samples.pb.Status\022\r\n\005val"
    "ue\030\002 \001(\014*4\n\006Status\022\007\n\003kOk\020\000\022\r\n\tkNotFound"
    "\020\001\022\022\n\016kInternalError\020\0022\325\001\n\010Database\022@\n\003g"
    "et\022\032.mimosa.rpc.samples.pb.Key\032\035.mimosa."
    "rpc.samples.pb.Result\022E\n\003set\022\037.mimosa.rp"
    "c.samples.pb.KeyValue\032\035.mimosa.rpc.sampl"
    "es.pb.Result\022@\n\003del\022\032.mimosa.rpc.samples"
    ".pb.Key\032\035.mimosa.rpc.samples.pb.Result", 438);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "kv-db.proto", &protobuf_RegisterTypes);
  Key::default_instance_ = new Key();
  KeyValue::default_instance_ = new KeyValue();
  Result::default_instance_ = new Result();
  Key::default_instance_->InitAsDefaultInstance();
  KeyValue::default_instance_->InitAsDefaultInstance();
  Result::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_kv_2ddb_2eproto);
}
void mimosa::rpc::samples::pb::protobuf_AssignDesc_kv_2ddb_2eproto ()
Definition at line 37 of file kv-db.pb.cc.
References protobuf_AddDesc_kv_2ddb_2eproto().
{
  protobuf_AddDesc_kv_2ddb_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "kv-db.proto");
  GOOGLE_CHECK(file != NULL);
  Key_descriptor_ = file->message_type(0);
  static const int Key_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Key, key_),
  };
  Key_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Key_descriptor_,
      Key::default_instance_,
      Key_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Key, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Key, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Key));
  KeyValue_descriptor_ = file->message_type(1);
  static const int KeyValue_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyValue, key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyValue, value_),
  };
  KeyValue_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      KeyValue_descriptor_,
      KeyValue::default_instance_,
      KeyValue_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyValue, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyValue, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(KeyValue));
  Result_descriptor_ = file->message_type(2);
  static const int Result_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Result, status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Result, value_),
  };
  Result_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Result_descriptor_,
      Result::default_instance_,
      Result_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Result, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Result, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Result));
  Status_descriptor_ = file->enum_type(0);
}
void mimosa::rpc::samples::pb::protobuf_ShutdownFile_kv_2ddb_2eproto ()
Definition at line 113 of file kv-db.pb.cc.
Referenced by protobuf_AddDesc_kv_2ddb_2eproto().
{
  delete Key::default_instance_;
  delete Key_reflection_;
  delete KeyValue::default_instance_;
  delete KeyValue_reflection_;
  delete Result::default_instance_;
  delete Result_reflection_;
}
const ::google::protobuf::EnumDescriptor * mimosa::rpc::samples::pb::Status_descriptor ()
Definition at line 158 of file kv-db.pb.cc.
Referenced by google::protobuf::GetEnumDescriptor< mimosa::rpc::samples::pb::Status >(), Status_Name(), and Status_Parse().
{
  protobuf_AssignDescriptorsOnce();
  return Status_descriptor_;
}
bool mimosa::rpc::samples::pb::Status_IsValid (int value)
Definition at line 162 of file kv-db.pb.cc.
Referenced by mimosa::rpc::samples::pb::Result::MergePartialFromCodedStream(), and mimosa::rpc::samples::pb::Result::set_status().
{
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}
const ::std::string& mimosa::rpc::samples::pb::Status_Name (Status value) [inline]
Definition at line 56 of file kv-db.pb.h.
References Status_descriptor().
{
  return ::google::protobuf::internal::NameOfEnum(
    Status_descriptor(), value);
}
bool mimosa::rpc::samples::pb::Status_Parse (const ::std::string & name, Status * value) [inline]
Definition at line 60 of file kv-db.pb.h.
References Status_descriptor(), and value.
{
  return ::google::protobuf::internal::ParseNamedEnum<Status>(
    Status_descriptor(), name, value);
}
Variable Documentation
struct mimosa::rpc::samples::pb::StaticDescriptorInitializer_kv_2ddb_2eproto mimosa::rpc::samples::pb::static_descriptor_initializer_kv_2ddb_2eproto_
const int mimosa::rpc::samples::pb::Status_ARRAYSIZE = Status_MAX + 1
Definition at line 53 of file kv-db.pb.h.
const Status mimosa::rpc::samples::pb::Status_MAX = kInternalError
Definition at line 52 of file kv-db.pb.h.
const Status mimosa::rpc::samples::pb::Status_MIN = kOk
Definition at line 51 of file kv-db.pb.h.