mimosa: mimosa::uri Namespace Reference
mimosa::uri Namespace Reference
Data Structures
class Url
Enumerations
enum EncodingType { kRfc2396, kRfc3986 }
Functions
void normalizePath (const char *const input, uint32_t const len, std::string *const output)
static void extractKeyValue (const char *&in, const char *const end, container::kvs *kvs)
void parseQuery (const char *const input, uint32_t const len, container::kvs *kvs)
static bool isValid (uint8_t c)
void percentEncode (const char *input, uint32_t input_len, std::string *output, EncodingType rfc)
static uint8_t xdigitValue (char c)
void percentDecode (const char *input, uint32_t input_len, std::string *output, EncodingType rfc)
Variables
static const uint64_t is_valid [4]
static const char hex [] = "0123456789ABCDEF"
Enumeration Type Documentation
enum mimosa::uri::EncodingType
Enumerator:
kRfc2396
kRfc3986
Definition at line 11 of file percent-encoding.hh.
    {
      kRfc2396, // encodes ' ' as '+', decodes '+' as ' '
      kRfc3986, // encodes ' ' as '%20', decodes '+' as '+'
    };
Function Documentation
static void mimosa::uri::extractKeyValue (const char *& in, const char *const end, container::kvs * kvs) [static]
Definition at line 7 of file parse-query.cc.
References key, and value.
Referenced by parseQuery().
    {
      const char * key     = in;
      const char * key_end = in;
      while (true)
      {
        if (in == end || *in == '&')
        {
          if (key < in)
            kvs->insert(std::make_pair(std::string(key, in - key),
                                       std::string()));
          return;
        }
        if (*in == '=')
        {
          key_end = in;
          break;
        }
        ++in;
      }
      const char * value     = ++in;
      while (true)
      {
        if (in == end || *in == '&')
        {
          if (key < key_end)
            kvs->insert(std::make_pair(std::string(key, key_end - key),
                                       std::string(value, in - value)));
          return;
        }
        ++in;
      }
    }
static bool mimosa::uri::isValid (uint8_t c) [static]
Definition at line 20 of file percent-encoding.cc.
References is_valid.
Referenced by percentEncode().
    {
      return is_valid[c >> 6] & (1ULL << (c & 0x3f));
    }
void mimosa::uri::normalizePath (const char *const input, uint32_t const len, std::string *const output)
Definition at line 10 of file normalize-path.cc.
References input().
Referenced by mimosa::http::Request::location().
    {
      std::vector<string::StringRef> stack;
      const char * const end = input + len;
      const char * in = input;
      bool is_root = (len > 0 && *input == '/');
      bool is_dir = false;
      while (in < end)
      {
        /* skip slashes */
        while (in < end && *in == '/')
            ++in;
        if (in == end)
        {
          is_dir = true;
          break;
        }
        const char * token = in;
        /* find slash */
        while (in < end && *in != '/')
          ++in;
        const char * token_end = in;
        switch (token_end - token)
        {
        case 1:
          if (token[0] == '.')
          {
            is_dir = true;
            continue;
          }
          break;
        case 2:
          if (token[0] == '.' && token[1] == '.')
          {
            if (!stack.empty())
              stack.pop_back();
            is_dir = true;
            continue;
          }
          break;
        }
        stack.push_back(string::StringRef(token, token_end));
        is_dir = false;
      }
      /* calculating size to reserve the string */
      uint32_t size = 0;
      for (auto it = stack.cbegin(); it != stack.cend(); ++it)
        size += it->size() + 1;
      output->clear();
      output->reserve(size);
      if (stack.empty())
      {
        output->push_back(is_root ? '/' : '.');
        return;
      }
      bool need_slash = is_root;
      for (auto it = stack.cbegin(); it != stack.cend(); ++it)
      {
        if (need_slash)
          output->push_back('/');
        else
          need_slash = true;
        output->append(it->data(), it->size());
      }
      if (is_dir)
        output->push_back('/');
    }
void mimosa::uri::parseQuery (const char *const input, uint32_t const len, container::kvs * kvs)
Definition at line 49 of file parse-query.cc.
References extractKeyValue(), and input().
Referenced by mimosa::http::RequestReader::form(), and mimosa::http::Request::query().
    {
      const char *       in  = input;
      const char * const end = input + len;
      while (in < end)
      {
        if (*in == '&')
        {
          ++in;
          continue;
        }
        extractKeyValue(in, end, kvs);
      }
    }
void mimosa::uri::percentDecode (const char * input, uint32_t input_len, std::string * output, EncodingType rfc)
Definition at line 64 of file percent-encoding.cc.
References input(), kRfc2396, and xdigitValue().
Referenced by mimosa::http::RequestReader::form(), mimosa::http::Request::location(), and mimosa::http::Request::query().
    {
      output->clear();
      output->resize(input_len);
      char *             out = &(*output)[0];
      const char * const end = input + input_len;
      for (; input < end; ++input, ++out)
      {
        uint8_t c = *input;
        if (rfc == kRfc2396 && c == '+')
          *out = ' ';
        else if (c == '%' && end - input > 2 && isxdigit(input[1]) && isxdigit(input[2]))
        {
          *out = (xdigitValue(input[1]) << 4) | xdigitValue(input[2]);
          input += 2;
        }
        else
          *out = *input;
      }
      output->resize(out - &(*output)[0]);
    }
void mimosa::uri::percentEncode (const char * input, uint32_t input_len, std::string * output, EncodingType rfc)
Definition at line 25 of file percent-encoding.cc.
References hex, input(), isValid(), and kRfc2396.
    {
      output->clear();
      output->resize(input_len * 3);
      char *             out = &(*output)[0];
      const char * const end = input + input_len;
      for (; input < end; ++input, ++out)
      {
        uint8_t c = *input;
        if (rfc == kRfc2396 && c == ' ')
          *out = '+';
        else if (isValid(c))
          *out = c;
        else
        {
          *out = '%';
          *++out = hex[c >> 4];
          *++out = hex[c & 0xf];
        }
      }
      output->resize(out - &(*output)[0]);
    }
static uint8_t mimosa::uri::xdigitValue (char c) [static]
Definition at line 53 of file percent-encoding.cc.
Referenced by percentDecode().
    {
      if ('0' <= c && c <= '9')
        return c - '0';
      if ('a' <= c && c <= 'f')
        return c - 'a' + 10;
      if ('A' <= c && c <= 'F')
        return c - 'A' + 10;
      return 0;
    }
Variable Documentation
const char mimosa::uri::hex[] = "0123456789ABCDEF" [static]
Definition at line 18 of file percent-encoding.cc.
Referenced by percentEncode().
const uint64_t mimosa::uri::is_valid[4] [static]
Initial value:
 {
      0b1010111111111111111101111101101000000000000000000000000000000001ULL,
      0b0100011111111111111111111111111010101111111111111111111111111111ULL,
      0b0000000000000000000000000000000000000000000000000000000000000000ULL,
      0b0000000000000000000000000000000000000000000000000000000000000000ULL,
    }
Definition at line 11 of file percent-encoding.cc.
Referenced by isValid().