mimosa: mimosa::runtime Namespace Reference
mimosa::runtime Namespace Reference
Data Structures
class Fiber
Typedefs
typedef ::melon_time_t Time
Functions
static void * startWrapper (std::function< void()> *fct)
Time time ()
Time nanoseconds (int64_t ns)
Time microseconds (int64_t us)
Time milliseconds (int64_t ms)
Time seconds (int64_t s)
Time minutes (int64_t m)
Time hours (int64_t h)
Time days (int64_t d)
void sleep (Time duration)
void yield ()
Typedef Documentation
typedef ::melon_time_t mimosa::runtime::Time
Definition at line 10 of file time.hh.
Function Documentation
Time mimosa::runtime::days (int64_t d) [inline]
Definition at line 18 of file time.hh.
{ return d * MELON_DAY; }
Time mimosa::runtime::hours (int64_t h) [inline]
Definition at line 17 of file time.hh.
{ return h * MELON_HOUR; }
Time mimosa::runtime::microseconds (int64_t us) [inline]
Definition at line 13 of file time.hh.
{ return us * MELON_MICROSECOND; }
Time mimosa::runtime::milliseconds (int64_t ms) [inline]
Definition at line 14 of file time.hh.
Referenced by mimosa::net::Server::stop().
{ return ms * MELON_MILLISECOND; }
Time mimosa::runtime::minutes (int64_t m) [inline]
Definition at line 16 of file time.hh.
Referenced by main().
{ return m * MELON_MINUTE; }
Time mimosa::runtime::nanoseconds (int64_t ns) [inline]
Definition at line 12 of file time.hh.
{ return ns * MELON_NANOSECOND; }
Time mimosa::runtime::seconds (int64_t s) [inline]
Definition at line 15 of file time.hh.
{ return s * MELON_SECOND; }
void mimosa::runtime::sleep (Time duration) [inline]
Definition at line 19 of file time.hh.
Referenced by main().
{ ::melon_usleep(duration / 1000); }
static void* mimosa::runtime::startWrapper (std::function< void()> * fct) [static]
Definition at line 7 of file fiber.cc.
Referenced by mimosa::runtime::Fiber::Fiber(), and mimosa::runtime::Fiber::start().
    {
      (*fct)();
      delete fct;
      return 0;
    }
Time mimosa::runtime::time () [inline]
Definition at line 11 of file time.hh.
Referenced by mimosa::net::Server::stop(), and mimosa::sync::Condition::wait().
{ return ::melon_time(); }
void mimosa::runtime::yield () [inline]
Definition at line 8 of file yield.hh.
{ ::melon_yield(); }