mimosa: mimosa Namespace Reference
mimosa Namespace Reference
Namespaces
namespace container
namespace http
namespace net
namespace rpc
namespace runtime
namespace stream
namespace string
namespace sync
namespace uri
Data Structures
struct GetFunction
class Function
class NonCopyable
class RefCountableBase
class RefCountable
class RefCountedPtr
Functions
template<typename Fct , typename... Args>
GetFunction< Fct, Args...>::Type bind (Fct fct, Args...args)
static int gnutls_mutex_init (void **mutex)
static int gnutls_mutex_lock (void **mutex)
static int gnutls_mutex_unlock (void **mutex)
static int gnutls_mutex_deinit (void **mutex)
void init (int argc, char **argv)
void wait ()
void deinit ()
void addRef (const RefCountableBase *obj)
void releaseRef (const RefCountableBase *obj)
Function Documentation
void mimosa::addRef (const RefCountableBase * obj) [inline]
Definition at line 47 of file ref-countable.hh.
References mimosa::RefCountableBase::addRef().
Referenced by mimosa::RefCountedPtr< T >::assign(), and mimosa::RefCountedPtr< T >::RefCountedPtr().
  {
    obj->addRef();
  }
template<typename Fct , typename... Args> GetFunction<Fct, Args...>::Type mimosa::bind (Fct fct, Args... args) [inline]
Definition at line 20 of file bind.hh.
Referenced by mimosa::net::Server::listenInet4(), mimosa::rpc::Server::Server(), and mimosa::http::Server::Server().
  {
    return new T(std::bind(fct, args...));
  }
void mimosa::deinit ()
Definition at line 63 of file init.cc.
References mimosa::runtime::Fiber::start().
  {
    runtime::Fiber::start([]() {
        ::gnutls_global_deinit ();
        google::ShutDownCommandLineFlags();
      });
    ::melon_wait();
  }
static int mimosa::gnutls_mutex_deinit (void ** mutex) [static]
Definition at line 36 of file init.cc.
Referenced by init().
  {
    ::melon_mutex ** m = reinterpret_cast< ::melon_mutex **>(mutex);
    assert(*m);
    ::melon_mutex_destroy(*m);
    return 0;
  }
static int mimosa::gnutls_mutex_init (void ** mutex) [static]
Definition at line 12 of file init.cc.
Referenced by init().
  {
    ::melon_mutex ** m = reinterpret_cast< ::melon_mutex **>(mutex);
    assert(m);
    *m = ::melon_mutex_new(0);
    return !*m;
  }
static int mimosa::gnutls_mutex_lock (void ** mutex) [static]
Definition at line 20 of file init.cc.
Referenced by init().
  {
    ::melon_mutex ** m = reinterpret_cast< ::melon_mutex **>(mutex);
    assert(*m);
    ::melon_mutex_lock(*m);
    return 0;
  }
static int mimosa::gnutls_mutex_unlock (void ** mutex) [static]
Definition at line 28 of file init.cc.
Referenced by init().
  {
    ::melon_mutex ** m = reinterpret_cast< ::melon_mutex **>(mutex);
    assert(*m);
    ::melon_mutex_unlock(*m);
    return 0;
  }
void mimosa::init (int argc, char ** argv)
Definition at line 44 of file init.cc.
References gnutls_mutex_deinit(), gnutls_mutex_init(), gnutls_mutex_lock(), gnutls_mutex_unlock(), and mimosa::runtime::Fiber::start().
  {
    if (::melon_init(0))
      throw int(0); // FIXME
    runtime::Fiber::start([&argv, &argc]() {
        google::ParseCommandLineFlags(&argc, &argv, true);
        ::gnutls_global_set_mutex(gnutls_mutex_init, gnutls_mutex_deinit,
                                  gnutls_mutex_lock, gnutls_mutex_unlock);
        ::gnutls_global_init();
      });
    ::melon_wait();
  }
void mimosa::releaseRef (const RefCountableBase * obj) [inline]
Definition at line 52 of file ref-countable.hh.
References mimosa::RefCountableBase::releaseRef().
Referenced by mimosa::RefCountedPtr< T >::assign().
  {
    if (obj->releaseRef() == 0)
      delete obj;
  }
void mimosa::wait ()
Definition at line 58 of file init.cc.
  {
    ::melon_wait();
  }