mimosa: mimosa/http/request-lexer.cc File Reference
request-lexer.cc File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <stdint.h>
#include <string>
#include "request-parser.hh"
#include <unistd.h>
Data Structures
struct yy_buffer_state
struct yy_trans_info
struct yyguts_t
Defines
#define YY_INT_ALIGNED long int
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#define FLEX_BETA
#define FLEXINT_H
#define INT8_MIN (-128)
#define INT16_MIN (-32767-1)
#define INT32_MIN (-2147483647-1)
#define INT8_MAX (127)
#define INT16_MAX (32767)
#define INT32_MAX (2147483647)
#define UINT8_MAX (255U)
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define yyconst
#define YY_NULL 0
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
#define YY_TYPEDEF_YY_SCANNER_T
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r
#define BEGIN yyg->yy_start = 1 + 2 *
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE mimosa_http_request_restart(yyin ,yyscanner)
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE 16384
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define YY_TYPEDEF_YY_BUFFER_STATE
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define YY_LESS_LINENO(n)
#define yyless(n)
#define unput(c) yyunput(c, yyg->yytext_ptr , yyscanner)
#define YY_TYPEDEF_YY_SIZE_T
#define YY_STRUCT_YY_BUFFER_STATE
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define YY_BUFFER_EOF_PENDING 2
#define YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
#define YY_FLUSH_BUFFER mimosa_http_request__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
#define yy_new_buffer mimosa_http_request__create_buffer
#define yy_set_interactive(is_interactive)
#define yy_set_bol(at_bol)
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define mimosa_http_request_wrap(n) 1
#define YY_SKIP_YYWRAP
#define yytext_ptr yytext_r
#define YY_DO_BEFORE_ACTION
#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define SAVE_TEXT
#define INITIAL 0
#define location 1
#define protover 2
#define proto_major 3
#define proto_minor 4
#define eol 5
#define key 6
#define value 7
#define value64 8
#define colon 9
#define value_accept_encoding 10
#define value_connection 11
#define value_cookie_attr 12
#define value_cookie_eq 13
#define value_cookie_value 14
#define value_cookie_str 15
#define value_cookie_sm 16
#define YY_EXTRA_TYPE std::string *
#define yylval yyg->yylval_r
#define YY_READ_BUF_SIZE 8192
#define ECHO do { if (fwrite(yytext, yyleng, 1, yyout)) {} } while (0)
#define YY_INPUT(buf, result, max_size)
#define yyterminate() return YY_NULL
#define YY_START_STACK_INCR 25
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg , yyscanner)
#define YY_DECL_IS_OURS 1
#define YY_DECL
#define YY_USER_ACTION
#define YY_BREAK break;
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_EXIT_FAILURE 2
#define yyless(n)
#define YYTABLES_NAME "yytables"
Typedefs
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef void * yyscan_t
typedef struct yy_buffer_state * YY_BUFFER_STATE
typedef size_t yy_size_t
typedef unsigned char YY_CHAR
typedef struct yy_trans_info * yy_state_type
Functions
void mimosa_http_request_restart (FILE *input_file, yyscan_t yyscanner)
void mimosa_http_request__switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
YY_BUFFER_STATE mimosa_http_request__create_buffer (FILE *file, int size, yyscan_t yyscanner)
void mimosa_http_request__delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
void mimosa_http_request__flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
void mimosa_http_request_push_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
void mimosa_http_request_pop_buffer_state (yyscan_t yyscanner)
static void mimosa_http_request_ensure_buffer_stack (yyscan_t yyscanner)
static void mimosa_http_request__load_buffer_state (yyscan_t yyscanner)
static void mimosa_http_request__init_buffer (YY_BUFFER_STATE b, FILE *file, yyscan_t yyscanner)
YY_BUFFER_STATE mimosa_http_request__scan_buffer (char *base, yy_size_t size, yyscan_t yyscanner)
YY_BUFFER_STATE mimosa_http_request__scan_string (char *yy_str, yyscan_t yyscanner)
YY_BUFFER_STATE mimosa_http_request__scan_bytes (char *bytes, int len, yyscan_t yyscanner)
void * mimosa_http_request_alloc (yy_size_t, yyscan_t yyscanner)
void * mimosa_http_request_realloc (void *, yy_size_t, yyscan_t yyscanner)
void mimosa_http_request_free (void *, yyscan_t yyscanner)
static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner)
static int yy_get_next_buffer (yyscan_t yyscanner)
static void yy_fatal_error (char msg[], yyscan_t yyscanner)
static int yy_init_globals (yyscan_t yyscanner)
int mimosa_http_request_lex_init (yyscan_t *scanner)
int mimosa_http_request_lex_init_extra (std::string *user_defined, yyscan_t *scanner)
int mimosa_http_request_lex_destroy (yyscan_t yyscanner)
int mimosa_http_request_get_debug (yyscan_t yyscanner)
void mimosa_http_request_set_debug (int debug_flag, yyscan_t yyscanner)
std::string * mimosa_http_request_get_extra (yyscan_t yyscanner)
void mimosa_http_request_set_extra (std::string *user_defined, yyscan_t yyscanner)
FILE * mimosa_http_request_get_in (yyscan_t yyscanner)
void mimosa_http_request_set_in (FILE *in_str, yyscan_t yyscanner)
FILE * mimosa_http_request_get_out (yyscan_t yyscanner)
void mimosa_http_request_set_out (FILE *out_str, yyscan_t yyscanner)
int mimosa_http_request_get_leng (yyscan_t yyscanner)
char * mimosa_http_request_get_text (yyscan_t yyscanner)
int mimosa_http_request_get_lineno (yyscan_t yyscanner)
void mimosa_http_request_set_lineno (int line_number, yyscan_t yyscanner)
int mimosa_http_request_get_column (yyscan_t yyscanner)
void mimosa_http_request_set_column (int column_no, yyscan_t yyscanner)
YYSTYPE * mimosa_http_request_get_lval (yyscan_t yyscanner)
void mimosa_http_request_set_lval (YYSTYPE *yylval_param, yyscan_t yyscanner)
static void yyunput (int c, char *buf_ptr, yyscan_t yyscanner)
static int input (yyscan_t yyscanner)
static void yy_push_state (int new_state, yyscan_t yyscanner)
static void yy_pop_state (yyscan_t yyscanner)
static int yy_top_state (yyscan_t yyscanner)
int mimosa_http_request_lex (YYSTYPE *yylval_param, yyscan_t yyscanner)
static void yyunput (int c, register char *yy_bp, yyscan_t yyscanner)
int isatty (int)
static void yy_fatal_error (char *msg, yyscan_t yyscanner)
Variables
static struct yy_trans_info yy_transition [21785]
static struct yy_trans_info * yy_start_state_list [35]
Define Documentation
#define BEGIN yyg->yy_start = 1 + 2 *
Definition at line 142 of file request-lexer.cc.
Referenced by mimosa_http_request_lex(), yy_pop_state(), and yy_push_state().
#define colon 9
Definition at line 5187 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define ECHO do { if (fwrite(yytext, yyleng, 1, yyout)) {} } while (0)
Definition at line 5337 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define EOB_ACT_CONTINUE_SCAN 0
Definition at line 173 of file request-lexer.cc.
Referenced by input(), mimosa_http_request_lex(), and yy_get_next_buffer().
#define EOB_ACT_END_OF_FILE 1
Definition at line 174 of file request-lexer.cc.
Referenced by input(), mimosa_http_request_lex(), and yy_get_next_buffer().
#define EOB_ACT_LAST_MATCH 2
Definition at line 175 of file request-lexer.cc.
Referenced by input(), mimosa_http_request_lex(), and yy_get_next_buffer().
#define eol 5
Definition at line 5183 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define FLEX_BETA
Definition at line 14 of file request-lexer.cc.
#define FLEX_SCANNER
Definition at line 9 of file request-lexer.cc.
#define FLEXINT_H
Definition at line 30 of file request-lexer.cc.
#define INITIAL 0
Definition at line 5178 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define INT16_MAX (32767)
Definition at line 73 of file request-lexer.cc.
#define INT16_MIN (-32767-1)
Definition at line 64 of file request-lexer.cc.
#define INT32_MAX (2147483647)
Definition at line 76 of file request-lexer.cc.
#define INT32_MIN (-2147483647-1)
Definition at line 67 of file request-lexer.cc.
#define INT8_MAX (127)
Definition at line 70 of file request-lexer.cc.
#define INT8_MIN (-128)
Definition at line 61 of file request-lexer.cc.
#define key 6
Definition at line 5184 of file request-lexer.cc.
Referenced by mimosa::uri::extractKeyValue(), and mimosa_http_request_lex().
#define location 1
Definition at line 5179 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define mimosa_http_request_wrap (n) 1
Definition at line 328 of file request-lexer.cc.
Referenced by input(), and mimosa_http_request_lex().
#define proto_major 3
Definition at line 5181 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define proto_minor 4
Definition at line 5182 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define protover 2
Definition at line 5180 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define REJECT reject_used_but_not_detected
Definition at line 5142 of file request-lexer.cc.
#define SAVE_TEXT
Value:
do {                                              \
    yylval->text = new std::string(yytext, yyleng); \
  } while (0)
Definition at line 5156 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define UINT16_MAX (65535U)
Definition at line 82 of file request-lexer.cc.
#define UINT32_MAX (4294967295U)
Definition at line 85 of file request-lexer.cc.
#define UINT8_MAX (255U)
Definition at line 79 of file request-lexer.cc.
#define unput (c) yyunput(c, yyg->yytext_ptr , yyscanner)
Definition at line 193 of file request-lexer.cc.
#define value 7
Definition at line 5185 of file request-lexer.cc.
Referenced by mimosa::uri::extractKeyValue(), mimosa_http_request_lex(), and mimosa::rpc::samples::pb::Status_Parse().
#define value64 8
Definition at line 5186 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define value_accept_encoding 10
Definition at line 5188 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define value_connection 11
Definition at line 5189 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define value_cookie_attr 12
Definition at line 5190 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define value_cookie_eq 13
Definition at line 5191 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define value_cookie_sm 16
Definition at line 5194 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define value_cookie_str 15
Definition at line 5193 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define value_cookie_value 14
Definition at line 5192 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define YY_AT_BOL () (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
Definition at line 324 of file request-lexer.cc.
#define YY_BREAK break;
Definition at line 5402 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define YY_BUF_SIZE 16384
Definition at line 161 of file request-lexer.cc.
Referenced by mimosa_http_request_lex(), and mimosa_http_request_restart().
#define YY_BUFFER_EOF_PENDING 2
Definition at line 260 of file request-lexer.cc.
Referenced by yy_get_next_buffer().
#define YY_BUFFER_NEW 0
Definition at line 248 of file request-lexer.cc.
Referenced by mimosa_http_request__flush_buffer(), mimosa_http_request__scan_buffer(), and mimosa_http_request_lex().
#define YY_BUFFER_NORMAL 1
Definition at line 249 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define YY_CURRENT_BUFFER
Value:
(yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
Definition at line 271 of file request-lexer.cc.
Referenced by mimosa_http_request__delete_buffer(), mimosa_http_request__flush_buffer(), mimosa_http_request__init_buffer(), mimosa_http_request__switch_to_buffer(), mimosa_http_request_get_column(), mimosa_http_request_get_lineno(), mimosa_http_request_lex(), mimosa_http_request_lex_destroy(), mimosa_http_request_pop_buffer_state(), mimosa_http_request_push_buffer_state(), mimosa_http_request_restart(), mimosa_http_request_set_column(), mimosa_http_request_set_lineno(), and yy_get_next_buffer().
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
Definition at line 278 of file request-lexer.cc.
Referenced by input(), mimosa_http_request__delete_buffer(), mimosa_http_request__load_buffer_state(), mimosa_http_request__switch_to_buffer(), mimosa_http_request_lex(), mimosa_http_request_lex_destroy(), mimosa_http_request_pop_buffer_state(), mimosa_http_request_push_buffer_state(), mimosa_http_request_restart(), yy_get_next_buffer(), and yyunput().
#define YY_DECL
Value:
int mimosa_http_request_lex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
Definition at line 5389 of file request-lexer.cc.
#define YY_DECL_IS_OURS 1
Definition at line 5384 of file request-lexer.cc.
#define YY_DO_BEFORE_ACTION
Value:
yyg->yytext_ptr = yy_bp; \
        yyleng = (size_t) (yy_cp - yy_bp); \
        yyg->yy_hold_char = *yy_cp; \
        *yy_cp = '\0'; \
        yyg->yy_c_buf_p = yy_cp;
Definition at line 345 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define YY_END_OF_BUFFER 46
Definition at line 353 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define YY_END_OF_BUFFER_CHAR 0
Definition at line 157 of file request-lexer.cc.
Referenced by input(), mimosa_http_request__flush_buffer(), mimosa_http_request__scan_buffer(), mimosa_http_request__scan_bytes(), and yy_get_next_buffer().
#define YY_EXIT_FAILURE 2
Definition at line 6590 of file request-lexer.cc.
Referenced by yy_fatal_error().
#define YY_EXTRA_TYPE std::string *
Definition at line 5204 of file request-lexer.cc.
#define YY_FATAL_ERROR (msg) yy_fatal_error(msg , yyscanner)
Definition at line 5375 of file request-lexer.cc.
Referenced by mimosa_http_request__create_buffer(), mimosa_http_request__scan_buffer(), mimosa_http_request__scan_bytes(), mimosa_http_request_ensure_buffer_stack(), mimosa_http_request_lex(), yy_get_next_buffer(), yy_pop_state(), yy_push_state(), and yyunput().
#define yy_flex_debug yyg->yy_flex_debug_r
Definition at line 136 of file request-lexer.cc.
Referenced by mimosa_http_request_get_debug(), and mimosa_http_request_set_debug().
#define YY_FLEX_MAJOR_VERSION 2
Definition at line 10 of file request-lexer.cc.
#define YY_FLEX_MINOR_VERSION 5
Definition at line 11 of file request-lexer.cc.
#define YY_FLEX_SUBMINOR_VERSION 35
Definition at line 12 of file request-lexer.cc.
#define YY_FLUSH_BUFFER mimosa_http_request__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
Definition at line 292 of file request-lexer.cc.
#define YY_INPUT (buf, result, max_size)
Value:
errno=0; \
        while ( (result = read( fileno(yyin), (char *) buf, max_size )) < 0 ) \
        { \
                if( errno != EINTR) \
                { \
                        YY_FATAL_ERROR( "input in flex scanner failed" ); \
                        break; \
                } \
                errno=0; \
                clearerr(yyin); \
        }\
\
Definition at line 5344 of file request-lexer.cc.
Referenced by yy_get_next_buffer().
#define YY_INT_ALIGNED long int
Definition at line 5 of file request-lexer.cc.
#define YY_LESS_LINENO (n)
Definition at line 177 of file request-lexer.cc.
#define YY_MORE_ADJ 0
Definition at line 5144 of file request-lexer.cc.
Referenced by mimosa_http_request_lex(), yy_get_next_buffer(), and yy_get_previous_state().
#define yy_new_buffer mimosa_http_request__create_buffer
Definition at line 302 of file request-lexer.cc.
#define YY_NEW_FILE mimosa_http_request_restart(yyin ,yyscanner)
Definition at line 155 of file request-lexer.cc.
Referenced by input(), and mimosa_http_request_lex().
#define YY_NULL 0
Definition at line 112 of file request-lexer.cc.
#define YY_NUM_RULES 45
Definition at line 352 of file request-lexer.cc.
#define YY_READ_BUF_SIZE 8192
Definition at line 5329 of file request-lexer.cc.
Referenced by yy_get_next_buffer().
#define YY_RESTORE_YY_MORE_OFFSET
Definition at line 5145 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define YY_RULE_SETUP YY_USER_ACTION
Definition at line 5405 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define YY_SC_TO_UI (c) ((unsigned int) (unsigned char) c)
Definition at line 119 of file request-lexer.cc.
Referenced by mimosa_http_request_lex(), and yy_get_previous_state().
#define yy_set_bol (at_bol)
Value:
{ \
        if ( ! YY_CURRENT_BUFFER ){\
        mimosa_http_request_ensure_buffer_stack (yyscanner); \
                YY_CURRENT_BUFFER_LVALUE =    \
            mimosa_http_request__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
        } \
        YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
        }
Definition at line 314 of file request-lexer.cc.
#define yy_set_interactive (is_interactive)
Value:
{ \
        if ( ! YY_CURRENT_BUFFER ){ \
        mimosa_http_request_ensure_buffer_stack (yyscanner); \
                YY_CURRENT_BUFFER_LVALUE =    \
            mimosa_http_request__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
        } \
        YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
        }
Definition at line 304 of file request-lexer.cc.
#define YY_SKIP_YYWRAP
Definition at line 329 of file request-lexer.cc.
#define YY_START ((yyg->yy_start - 1) / 2)
Definition at line 148 of file request-lexer.cc.
Referenced by mimosa_http_request_lex(), and yy_push_state().
#define YY_START_STACK_INCR 25
Definition at line 5370 of file request-lexer.cc.
Referenced by yy_push_state().
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
Definition at line 166 of file request-lexer.cc.
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
Definition at line 152 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define YY_STRUCT_YY_BUFFER_STATE
Definition at line 201 of file request-lexer.cc.
#define YY_TYPEDEF_YY_BUFFER_STATE
Definition at line 169 of file request-lexer.cc.
#define YY_TYPEDEF_YY_SCANNER_T
Definition at line 123 of file request-lexer.cc.
#define YY_TYPEDEF_YY_SIZE_T
Definition at line 196 of file request-lexer.cc.
#define YY_USER_ACTION
Definition at line 5397 of file request-lexer.cc.
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
Definition at line 135 of file request-lexer.cc.
Referenced by mimosa_http_request_get_column(), and mimosa_http_request_set_column().
#define yyconst
Definition at line 108 of file request-lexer.cc.
Referenced by mimosa_http_request_lex(), and yy_try_NUL_trans().
#define yyextra yyg->yyextra_r
Definition at line 131 of file request-lexer.cc.
Referenced by mimosa_http_request_get_extra(), mimosa_http_request_lex(), and mimosa_http_request_set_extra().
#define yyin yyg->yyin_r
Definition at line 129 of file request-lexer.cc.
Referenced by input(), mimosa_http_request__load_buffer_state(), mimosa_http_request_get_in(), mimosa_http_request_lex(), mimosa_http_request_restart(), mimosa_http_request_set_in(), yy_get_next_buffer(), and yy_init_globals().
#define yyleng yyg->yyleng_r
Definition at line 132 of file request-lexer.cc.
Referenced by mimosa_http_request_get_leng(), and mimosa_http_request_lex().
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
                *yy_cp = yyg->yy_hold_char; \
                YY_RESTORE_YY_MORE_OFFSET \
                yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
                YY_DO_BEFORE_ACTION; /* set up yytext again */ \
                } \
        while ( 0 )
Definition at line 6602 of file request-lexer.cc.
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
                yytext[yyleng] = yyg->yy_hold_char; \
                yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
                yyg->yy_hold_char = *yyg->yy_c_buf_p; \
                *yyg->yy_c_buf_p = '\0'; \
                yyleng = yyless_macro_arg; \
                } \
        while ( 0 )
Definition at line 6602 of file request-lexer.cc.
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
Definition at line 134 of file request-lexer.cc.
Referenced by mimosa_http_request_get_lineno(), and mimosa_http_request_set_lineno().
#define yylval yyg->yylval_r
Definition at line 5246 of file request-lexer.cc.
Referenced by mimosa_http_request_get_lval(), mimosa_http_request_lex(), and mimosa_http_request_set_lval().
#define yymore () yymore_used_but_not_detected
Definition at line 5143 of file request-lexer.cc.
#define yyout yyg->yyout_r
Definition at line 130 of file request-lexer.cc.
Referenced by mimosa_http_request_get_out(), mimosa_http_request_lex(), mimosa_http_request_set_out(), and yy_init_globals().
#define YYSTATE YY_START
Definition at line 149 of file request-lexer.cc.
#define YYTABLES_NAME "yytables"
Definition at line 6947 of file request-lexer.cc.
#define yyterminate () return YY_NULL
Definition at line 5365 of file request-lexer.cc.
Referenced by mimosa_http_request_lex().
#define yytext yyg->yytext_r
Definition at line 133 of file request-lexer.cc.
Referenced by mimosa_http_request_get_text(), and mimosa_http_request_lex().
#define yytext_ptr yytext_r
Definition at line 335 of file request-lexer.cc.
Typedef Documentation
typedef short int flex_int16_t
Definition at line 52 of file request-lexer.cc.
typedef int flex_int32_t
Definition at line 53 of file request-lexer.cc.
typedef signed char flex_int8_t
Definition at line 51 of file request-lexer.cc.
typedef unsigned short int flex_uint16_t
Definition at line 55 of file request-lexer.cc.
typedef unsigned int flex_uint32_t
Definition at line 56 of file request-lexer.cc.
typedef unsigned char flex_uint8_t
Definition at line 54 of file request-lexer.cc.
typedef struct yy_buffer_state* YY_BUFFER_STATE
Definition at line 170 of file request-lexer.cc.
typedef unsigned char YY_CHAR
Definition at line 331 of file request-lexer.cc.
typedef size_t yy_size_t
Definition at line 197 of file request-lexer.cc.
typedef struct yy_trans_info* yy_state_type
Definition at line 333 of file request-lexer.cc.
typedef void* yyscan_t
Definition at line 124 of file request-lexer.cc.
Function Documentation
static int input (yyscan_t yyscanner) [static]
Definition at line 6116 of file request-lexer.cc.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, mimosa_http_request_restart(), mimosa_http_request_wrap, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, YY_END_OF_BUFFER_CHAR, yy_get_next_buffer(), yyguts_t::yy_hold_char, yyguts_t::yy_n_chars, YY_NEW_FILE, and yyin.
Referenced by mimosa::uri::normalizePath(), mimosa::uri::parseQuery(), mimosa::uri::percentDecode(), and mimosa::uri::percentEncode().
{
        int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        *yyg->yy_c_buf_p = yyg->yy_hold_char;
        if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
                {
                /* yy_c_buf_p now points to the character we want to return.
                 * If this occurs *before* the EOB characters, then it's a
                 * valid NUL; if not, then we've hit the end of the buffer.
                 */
                if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
                        /* This was really a NUL. */
                        *yyg->yy_c_buf_p = '\0';
                else
                        { /* need more input */
                        int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
                        ++yyg->yy_c_buf_p;
                        switch ( yy_get_next_buffer( yyscanner ) )
{
                                case EOB_ACT_LAST_MATCH:
                                        /* This happens because yy_g_n_b()
                                         * sees that we've accumulated a
                                         * token and flags that we need to
                                         * try matching the token before
                                         * proceeding.  But for input(),
                                         * there's no matching to consider.
                                         * So convert the EOB_ACT_LAST_MATCH
                                         * to EOB_ACT_END_OF_FILE.
                                         */
                                        /* Reset buffer status. */
                                        mimosa_http_request_restart(yyin ,yyscanner);
                                        /*FALLTHROUGH*/
                                case EOB_ACT_END_OF_FILE:
{
                                        if ( mimosa_http_request_wrap(yyscanner ) )
                                                return EOF;
                                        if ( ! yyg->yy_did_buffer_switch_on_eof )
                                                YY_NEW_FILE;
#ifdef __cplusplus
                                        return yyinput(yyscanner);
#else
                                        return input(yyscanner);
#endif
                                        }
                                case EOB_ACT_CONTINUE_SCAN:
                                        yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
                                        break;
                                }
                        }
                }
        c = *(unsigned char *) yyg->yy_c_buf_p; /* cast for 8-bit char's */
        *yyg->yy_c_buf_p = '\0';        /* preserve yytext */
        yyg->yy_hold_char = *++yyg->yy_c_buf_p;
        return c;
}
int isatty (int)
Referenced by mimosa_http_request__init_buffer().
YY_BUFFER_STATE mimosa_http_request__create_buffer (FILE * file, int size, yyscan_t yyscanner)
Allocate and initialize an input buffer state.
Parameters:
file A readable stream.
size The character buffer size in bytes. When in doubt, use YY_BUF_SIZE.
yyscanner The scanner object.
Returns:
the allocated buffer state.
Definition at line 6257 of file request-lexer.cc.
References mimosa_http_request__init_buffer(), mimosa_http_request_alloc(), yy_buffer_state::yy_buf_size, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, yy_buffer_state::yy_is_our_buffer, and yyscanner.
Referenced by mimosa_http_request_lex(), and mimosa_http_request_restart().
{
        YY_BUFFER_STATE b;
        b = (YY_BUFFER_STATE) mimosa_http_request_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
        if ( ! b )
                YY_FATAL_ERROR( "out of dynamic memory in mimosa_http_request__create_buffer()" );
        b->yy_buf_size = size;
        /* yy_ch_buf has to be 2 characters longer than the size given because
         * we need to put in 2 end-of-buffer characters.
         */
        b->yy_ch_buf = (char *) mimosa_http_request_alloc(b->yy_buf_size + 2 ,yyscanner );
        if ( ! b->yy_ch_buf )
                YY_FATAL_ERROR( "out of dynamic memory in mimosa_http_request__create_buffer()" );
        b->yy_is_our_buffer = 1;
        mimosa_http_request__init_buffer(b,file ,yyscanner);
        return b;
}
void mimosa_http_request__delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Destroy the buffer.
Parameters:
b a buffer created with mimosa_http_request__create_buffer()
yyscanner The scanner object.
Definition at line 6285 of file request-lexer.cc.
References mimosa_http_request_free(), yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yy_buffer_state::yy_is_our_buffer.
Referenced by mimosa_http_request_lex_destroy(), and mimosa_http_request_pop_buffer_state().
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        if ( ! b )
                return;
        if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
                YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;
        if ( b->yy_is_our_buffer )
                mimosa_http_request_free((void *) b->yy_ch_buf ,yyscanner );
        mimosa_http_request_free((void *) b ,yyscanner );
}
void mimosa_http_request__flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters. On the next scan, YY_INPUT will be called.
Parameters:
b the buffer state to be flushed, usually YY_CURRENT_BUFFER.
yyscanner The scanner object.
Definition at line 6338 of file request-lexer.cc.
References mimosa_http_request__load_buffer_state(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_END_OF_BUFFER_CHAR, and yy_buffer_state::yy_n_chars.
Referenced by mimosa_http_request__init_buffer().
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        if ( ! b )
                return;
        b->yy_n_chars = 0;
        /* We always need two end-of-buffer characters.  The first causes
         * a transition to the end-of-buffer state.  The second causes
         * a jam in that state.
         */
        b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
        b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
        b->yy_buf_pos = &b->yy_ch_buf[0];
        b->yy_at_bol = 1;
        b->yy_buffer_status = YY_BUFFER_NEW;
        if ( b == YY_CURRENT_BUFFER )
                mimosa_http_request__load_buffer_state(yyscanner );
}
static void mimosa_http_request__init_buffer (YY_BUFFER_STATE b, FILE * file, yyscan_t yyscanner) [static]
Definition at line 6309 of file request-lexer.cc.
References isatty(), mimosa_http_request__flush_buffer(), yy_buffer_state::yy_bs_column, yy_buffer_state::yy_bs_lineno, YY_CURRENT_BUFFER, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, and yy_buffer_state::yy_is_interactive.
Referenced by mimosa_http_request__create_buffer(), and mimosa_http_request_restart().
{
        int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        mimosa_http_request__flush_buffer(b ,yyscanner);
        b->yy_input_file = file;
        b->yy_fill_buffer = 1;
    /* If b is the current buffer, then mimosa_http_request__init_buffer was _probably_
     * called from mimosa_http_request_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }
        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
        errno = oerrno;
}
static void mimosa_http_request__load_buffer_state (yyscan_t yyscanner) [static]
Definition at line 6242 of file request-lexer.cc.
References yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars, and yyin.
Referenced by mimosa_http_request__flush_buffer(), mimosa_http_request__switch_to_buffer(), mimosa_http_request_lex(), mimosa_http_request_pop_buffer_state(), mimosa_http_request_push_buffer_state(), and mimosa_http_request_restart().
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
        yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
        yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
        yyg->yy_hold_char = *yyg->yy_c_buf_p;
}
YY_BUFFER_STATE mimosa_http_request__scan_buffer (char * base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer.
Parameters:
base the character buffer
size the size in bytes of the character buffer
yyscanner The scanner object.
Returns:
the newly allocated buffer state object.
Definition at line 6469 of file request-lexer.cc.
References mimosa_http_request__switch_to_buffer(), mimosa_http_request_alloc(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buf_size, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, yy_buffer_state::yy_n_chars, and yyscanner.
Referenced by mimosa_http_request__scan_bytes().
{
        YY_BUFFER_STATE b;
        if ( size < 2 ||
             base[size-2] != YY_END_OF_BUFFER_CHAR ||
             base[size-1] != YY_END_OF_BUFFER_CHAR )
                /* They forgot to leave room for the EOB's. */
                return 0;
        b = (YY_BUFFER_STATE) mimosa_http_request_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
        if ( ! b )
                YY_FATAL_ERROR( "out of dynamic memory in mimosa_http_request__scan_buffer()" );
        b->yy_buf_size = size - 2;      /* "- 2" to take care of EOB's */
        b->yy_buf_pos = b->yy_ch_buf = base;
        b->yy_is_our_buffer = 0;
        b->yy_input_file = 0;
        b->yy_n_chars = b->yy_buf_size;
        b->yy_is_interactive = 0;
        b->yy_at_bol = 1;
        b->yy_fill_buffer = 0;
        b->yy_buffer_status = YY_BUFFER_NEW;
        mimosa_http_request__switch_to_buffer(b ,yyscanner );
        return b;
}
YY_BUFFER_STATE mimosa_http_request__scan_bytes (char * yybytes, int _yybytes_len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes. The next call to mimosa_http_request_lex() will scan from a copy of bytes.
Parameters:
bytes the byte buffer to scan
len the number of bytes in the buffer pointed to by bytes.
yyscanner The scanner object.
Returns:
the newly allocated buffer state object.
Definition at line 6519 of file request-lexer.cc.
References mimosa_http_request__scan_buffer(), mimosa_http_request_alloc(), YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, and yy_buffer_state::yy_is_our_buffer.
Referenced by mimosa_http_request__scan_string().
{
        YY_BUFFER_STATE b;
        char *buf;
        yy_size_t n;
        int i;
        /* Get memory for full buffer, including space for trailing EOB's. */
        n = _yybytes_len + 2;
        buf = (char *) mimosa_http_request_alloc(n ,yyscanner );
        if ( ! buf )
                YY_FATAL_ERROR( "out of dynamic memory in mimosa_http_request__scan_bytes()" );
        for ( i = 0; i < _yybytes_len; ++i )
                buf[i] = yybytes[i];
        buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;
        b = mimosa_http_request__scan_buffer(buf,n ,yyscanner);
        if ( ! b )
                YY_FATAL_ERROR( "bad buffer in mimosa_http_request__scan_bytes()" );
        /* It's okay to grow etc. this buffer, and we should throw it
         * away when we're done.
         */
        b->yy_is_our_buffer = 1;
        return b;
}
YY_BUFFER_STATE mimosa_http_request__scan_string (char * yystr, yyscan_t yyscanner)
Setup the input buffer state to scan a string. The next call to mimosa_http_request_lex() will scan from a copy of str.
Parameters:
yystr a NUL-terminated string to scan
yyscanner The scanner object.
Returns:
the newly allocated buffer state object.
Note:
If you want to scan bytes that may contain NUL values, then use mimosa_http_request__scan_bytes() instead.
Definition at line 6506 of file request-lexer.cc.
References mimosa_http_request__scan_bytes().
{
        return mimosa_http_request__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}
void mimosa_http_request__switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Switch to a different input buffer.
Parameters:
new_buffer The new input buffer.
yyscanner The scanner object.
Definition at line 6210 of file request-lexer.cc.
References mimosa_http_request__load_buffer_state(), mimosa_http_request_ensure_buffer_stack(), yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, and yyguts_t::yy_n_chars.
Referenced by mimosa_http_request__scan_buffer().
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        /* TODO. We should be able to replace this entire function body
         * with
         *              mimosa_http_request_pop_buffer_state();
         *              mimosa_http_request_push_buffer_state(new_buffer);
     */
        mimosa_http_request_ensure_buffer_stack (yyscanner);
        if ( YY_CURRENT_BUFFER == new_buffer )
                return;
        if ( YY_CURRENT_BUFFER )
                {
                /* Flush out information for old buffer. */
                *yyg->yy_c_buf_p = yyg->yy_hold_char;
                YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
                YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
                }
        YY_CURRENT_BUFFER_LVALUE = new_buffer;
        mimosa_http_request__load_buffer_state(yyscanner );
        /* We don't actually know whether we did this switch during
         * EOF (mimosa_http_request_wrap()) processing, but the only time this flag
         * is looked at is after mimosa_http_request_wrap() is called, so it's safe
         * to go ahead and always set it.
         */
        yyg->yy_did_buffer_switch_on_eof = 1;
}
void * mimosa_http_request_alloc (yy_size_t size, yyscan_t yyscanner)
Definition at line 6925 of file request-lexer.cc.
Referenced by mimosa_http_request__create_buffer(), mimosa_http_request__scan_buffer(), mimosa_http_request__scan_bytes(), mimosa_http_request_ensure_buffer_stack(), mimosa_http_request_lex_init(), mimosa_http_request_lex_init_extra(), and yy_push_state().
{
        return (void *) malloc( size );
}
static void mimosa_http_request_ensure_buffer_stack (yyscan_t yyscanner) [static]
Definition at line 6419 of file request-lexer.cc.
References mimosa_http_request_alloc(), mimosa_http_request_realloc(), yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, YY_FATAL_ERROR, and yyscanner.
Referenced by mimosa_http_request__switch_to_buffer(), mimosa_http_request_lex(), mimosa_http_request_push_buffer_state(), and mimosa_http_request_restart().
{
        int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        if (!yyg->yy_buffer_stack) {
                /* First allocation is just for 2 elements, since we don't know if this
                 * scanner will even need a stack. We use 2 instead of 1 to avoid an
                 * immediate realloc on the next call.
         */
                num_to_alloc = 1;
                yyg->yy_buffer_stack = (struct yy_buffer_state**)mimosa_http_request_alloc
                                                                (num_to_alloc * sizeof(struct yy_buffer_state*)
                                                                , yyscanner);
                if ( ! yyg->yy_buffer_stack )
                        YY_FATAL_ERROR( "out of dynamic memory in mimosa_http_request_ensure_buffer_stack()" );
                memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
                yyg->yy_buffer_stack_max = num_to_alloc;
                yyg->yy_buffer_stack_top = 0;
                return;
        }
        if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){
                /* Increase the buffer to prepare for a possible push. */
                int grow_size = 8 /* arbitrary grow size */;
                num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
                yyg->yy_buffer_stack = (struct yy_buffer_state**)mimosa_http_request_realloc
                                                                (yyg->yy_buffer_stack,
                                                                num_to_alloc * sizeof(struct yy_buffer_state*)
                                                                , yyscanner);
                if ( ! yyg->yy_buffer_stack )
                        YY_FATAL_ERROR( "out of dynamic memory in mimosa_http_request_ensure_buffer_stack()" );
                /* zero only the new slots.*/
                memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
                yyg->yy_buffer_stack_max = num_to_alloc;
        }
}
void mimosa_http_request_free (void * ptr, yyscan_t yyscanner)
Definition at line 6942 of file request-lexer.cc.
Referenced by mimosa_http_request__delete_buffer(), and mimosa_http_request_lex_destroy().
{
        free( (char *) ptr );   /* see mimosa_http_request_realloc() for (char *) cast */
}
int mimosa_http_request_get_column (yyscan_t yyscanner)
Get the current column number.
Parameters:
yyscanner The scanner object.
Definition at line 6643 of file request-lexer.cc.
References YY_CURRENT_BUFFER, and yycolumn.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        if (! YY_CURRENT_BUFFER)
            return 0;
    return yycolumn;
}
int mimosa_http_request_get_debug (yyscan_t yyscanner)
Definition at line 6748 of file request-lexer.cc.
References yy_flex_debug.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}
std::string * mimosa_http_request_get_extra (yyscan_t yyscanner)
Get the user-defined data for this scanner.
Parameters:
yyscanner The scanner object.
Definition at line 6621 of file request-lexer.cc.
References yyextra.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}
FILE * mimosa_http_request_get_in (yyscan_t yyscanner)
Get the input stream.
Parameters:
yyscanner The scanner object.
Definition at line 6656 of file request-lexer.cc.
References yyin.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}
int mimosa_http_request_get_leng (yyscan_t yyscanner)
Get the length of the current token.
Parameters:
yyscanner The scanner object.
Definition at line 6674 of file request-lexer.cc.
References yyleng.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}
int mimosa_http_request_get_lineno (yyscan_t yyscanner)
Get the current line number.
Parameters:
yyscanner The scanner object.
Definition at line 6630 of file request-lexer.cc.
References YY_CURRENT_BUFFER, and yylineno.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        if (! YY_CURRENT_BUFFER)
            return 0;
    return yylineno;
}
YYSTYPE * mimosa_http_request_get_lval (yyscan_t yyscanner)
Definition at line 6762 of file request-lexer.cc.
References yylval.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}
FILE * mimosa_http_request_get_out (yyscan_t yyscanner)
Get the output stream.
Parameters:
yyscanner The scanner object.
Definition at line 6665 of file request-lexer.cc.
References yyout.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}
char * mimosa_http_request_get_text (yyscan_t yyscanner)
Get the current token.
Parameters:
yyscanner The scanner object.
Definition at line 6684 of file request-lexer.cc.
References yytext.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}
int mimosa_http_request_lex (YYSTYPE * yylval_param, yyscan_t yyscanner)
The main scanner function which does all the work.
Definition at line 5410 of file request-lexer.cc.
References ATTR, BEGIN, colon, COMPRESS, CONNECT, DEFLATE, DELETE, ECHO, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, eol, GET, GZIP, HEAD, IDENTITY, INITIAL, KEY, key, KEY_ACCEPT_ENCODING, KEY_CONNECTION, KEY_CONTENT_LENGTH, KEY_CONTENT_TYPE, KEY_COOKIE, KEY_HOST, KEY_REFERRER, KEY_USER_AGENT, LOCATION, location, mimosa_http_request__create_buffer(), mimosa_http_request__load_buffer_state(), mimosa_http_request_ensure_buffer_stack(), mimosa_http_request_wrap, OPTIONS, PATCH, POST, PROTO_MAJOR, proto_major, PROTO_MINOR, proto_minor, protover, PUT, SAVE_TEXT, TRACE, VAL64, VALUE, value, value64, value_accept_encoding, VALUE_CONNECTION, value_connection, value_cookie_attr, value_cookie_eq, value_cookie_sm, value_cookie_str, value_cookie_value, YY_BREAK, YY_BUF_SIZE, YY_BUFFER_NEW, YY_BUFFER_NORMAL, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, YY_DO_BEFORE_ACTION, YY_END_OF_BUFFER, YY_FATAL_ERROR, yy_get_next_buffer(), yy_get_previous_state(), yyguts_t::yy_hold_char, yyguts_t::yy_init, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, YY_MORE_ADJ, yyguts_t::yy_n_chars, YY_NEW_FILE, yy_trans_info::yy_nxt, YY_RESTORE_YY_MORE_OFFSET, YY_RULE_SETUP, YY_SC_TO_UI, YY_START, yyguts_t::yy_start, YY_STATE_EOF, yy_try_NUL_trans(), yy_trans_info::yy_verify, yyconst, yyextra, yyin, yyleng, yylval, yyout, yyscanner, yyterminate, and yytext.
{
        register yy_state_type yy_current_state;
        register char *yy_cp, *yy_bp;
        register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
#line 46 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
#line 5421 "request-lexer.cc"
    yylval = yylval_param;
        if ( !yyg->yy_init )
                {
                yyg->yy_init = 1;
#ifdef YY_USER_INIT
                YY_USER_INIT;
#endif
                if ( ! yyg->yy_start )
                        yyg->yy_start = 1;      /* first start state */
                if ( ! yyin )
                        yyin = stdin;
                if ( ! yyout )
                        yyout = stdout;
                if ( ! YY_CURRENT_BUFFER ) {
                        mimosa_http_request_ensure_buffer_stack (yyscanner);
                        YY_CURRENT_BUFFER_LVALUE =
                                mimosa_http_request__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
                }
                mimosa_http_request__load_buffer_state(yyscanner );
                }
        while ( 1 )             /* loops until end-of-file is reached */
                {
                yy_cp = yyg->yy_c_buf_p;
                /* Support of yytext. */
                *yy_cp = yyg->yy_hold_char;
                /* yy_bp points to the position in yy_ch_buf of the start of
                 * the current run.
                 */
                yy_bp = yy_cp;
                yy_current_state = yy_start_state_list[yyg->yy_start];
yy_match:
                {
                register yyconst struct yy_trans_info *yy_trans_info;
                register YY_CHAR yy_c;
                for ( yy_c = YY_SC_TO_UI(*yy_cp);
                      (yy_trans_info = &yy_current_state[(unsigned int) yy_c])->
                yy_verify == yy_c;
                      yy_c = YY_SC_TO_UI(*++yy_cp) )
{
                        yy_current_state += yy_trans_info->yy_nxt;
                        if ( yy_current_state[-1].yy_nxt )
{
                                yyg->yy_last_accepting_state = yy_current_state;
                                yyg->yy_last_accepting_cpos = yy_cp;
                                }
                        }
                }
yy_find_action:
                yy_act = yy_current_state[-1].yy_nxt;
                YY_DO_BEFORE_ACTION;
do_action:      /* This label is used only to access EOF actions. */
                switch ( yy_act )
        { /* beginning of action switch */
                        case 0: /* must back up */
                        /* undo the effects of YY_DO_BEFORE_ACTION */
                        *yy_cp = yyg->yy_hold_char;
                        yy_cp = yyg->yy_last_accepting_cpos + 1;
                        yy_current_state = yyg->yy_last_accepting_state;
                        goto yy_find_action;
case 1:
YY_RULE_SETUP
#line 48 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(location); return HEAD;
        YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(location); return GET;
        YY_BREAK
case 3:
YY_RULE_SETUP
#line 50 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(location); return POST;
        YY_BREAK
case 4:
YY_RULE_SETUP
#line 51 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(location); return PUT;
        YY_BREAK
case 5:
YY_RULE_SETUP
#line 52 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(location); return DELETE;
        YY_BREAK
case 6:
YY_RULE_SETUP
#line 53 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(location); return TRACE;
        YY_BREAK
case 7:
YY_RULE_SETUP
#line 54 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(location); return OPTIONS;
        YY_BREAK
case 8:
YY_RULE_SETUP
#line 55 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(location); return CONNECT;
        YY_BREAK
case 9:
YY_RULE_SETUP
#line 56 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(location); return PATCH;
        YY_BREAK
case 10:
YY_RULE_SETUP
#line 58 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(protover); SAVE_TEXT; return LOCATION;
        YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(proto_major);
        YY_BREAK
case 12:
YY_RULE_SETUP
#line 61 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(proto_minor); return PROTO_MAJOR;
        YY_BREAK
case 13:
YY_RULE_SETUP
#line 62 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(eol); return PROTO_MINOR;
        YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(value_accept_encoding); return KEY_ACCEPT_ENCODING;
        YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(value_connection); return KEY_CONNECTION;
        YY_BREAK
case 16:
YY_RULE_SETUP
#line 67 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(value_cookie_attr); return KEY_COOKIE;
        YY_BREAK
case 17:
YY_RULE_SETUP
#line 68 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(value64); return KEY_CONTENT_LENGTH;
        YY_BREAK
case 18:
YY_RULE_SETUP
#line 69 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(colon); return KEY_CONTENT_TYPE;
        YY_BREAK
case 19:
YY_RULE_SETUP
#line 70 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(colon); return KEY_HOST;
        YY_BREAK
case 20:
YY_RULE_SETUP
#line 71 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(colon); return KEY_REFERRER;
        YY_BREAK
case 21:
YY_RULE_SETUP
#line 72 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(colon); return KEY_USER_AGENT;
        YY_BREAK
case 22:
YY_RULE_SETUP
#line 73 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(colon); SAVE_TEXT; return KEY;
        YY_BREAK
case 23:
YY_RULE_SETUP
#line 75 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(value);
        YY_BREAK
case 24:
/* rule 24 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 77 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
SAVE_TEXT; return VALUE;
        YY_BREAK
case 25:
YY_RULE_SETUP
#line 79 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
return COMPRESS;
        YY_BREAK
case 26:
YY_RULE_SETUP
#line 80 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
return IDENTITY;
        YY_BREAK
case 27:
YY_RULE_SETUP
#line 81 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
return DEFLATE;
        YY_BREAK
case 28:
YY_RULE_SETUP
#line 82 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
return GZIP;
        YY_BREAK
case 29:
YY_RULE_SETUP
#line 83 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
        YY_BREAK
case 30:
YY_RULE_SETUP
#line 85 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(value_cookie_eq); SAVE_TEXT; return ATTR;
        YY_BREAK
case 31:
YY_RULE_SETUP
#line 86 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(value_cookie_value); return '=';
        YY_BREAK
case 32:
YY_RULE_SETUP
#line 87 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(value_cookie_attr); return ';';
        YY_BREAK
case 33:
YY_RULE_SETUP
#line 88 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(value_cookie_sm); SAVE_TEXT; return VALUE;
        YY_BREAK
case 34:
YY_RULE_SETUP
#line 89 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(value_cookie_str); yyextra->clear();
        YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 90 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
yyextra->append(yytext, yyleng);
        YY_BREAK
case 36:
YY_RULE_SETUP
#line 91 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
yyextra->push_back(yytext[1]);
        YY_BREAK
case 37:
YY_RULE_SETUP
#line 92 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(value_cookie_sm); yylval->text = new std::string(*yyextra); return VALUE;
        YY_BREAK
case 38:
YY_RULE_SETUP
#line 94 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
yylval->ival = 1; return VALUE_CONNECTION;
        YY_BREAK
case 39:
YY_RULE_SETUP
#line 95 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
yylval->ival = 0; return VALUE_CONNECTION;
        YY_BREAK
case 40:
YY_RULE_SETUP
#line 97 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
yylval->val64 = strtoll(yytext, 0, 0); return VAL64;
        YY_BREAK
case 41:
YY_RULE_SETUP
#line 99 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
/* ignore */
        YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 100 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
yyterminate();
        YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 101 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
BEGIN(key);
        YY_BREAK
case 44:
YY_RULE_SETUP
#line 102 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
yyterminate();
        YY_BREAK
case 45:
YY_RULE_SETUP
#line 103 "/home/abique/develop/mimosa/mimosa/http/request-lexer.l"
ECHO;
        YY_BREAK
#line 5733 "request-lexer.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(location):
case YY_STATE_EOF(protover):
case YY_STATE_EOF(proto_major):
case YY_STATE_EOF(proto_minor):
case YY_STATE_EOF(eol):
case YY_STATE_EOF(key):
case YY_STATE_EOF(value):
case YY_STATE_EOF(value64):
case YY_STATE_EOF(colon):
case YY_STATE_EOF(value_accept_encoding):
case YY_STATE_EOF(value_connection):
case YY_STATE_EOF(value_cookie_attr):
case YY_STATE_EOF(value_cookie_eq):
case YY_STATE_EOF(value_cookie_value):
case YY_STATE_EOF(value_cookie_str):
case YY_STATE_EOF(value_cookie_sm):
        yyterminate();
        case YY_END_OF_BUFFER:
                {
                /* Amount of text matched not including the EOB char. */
                int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;
                /* Undo the effects of YY_DO_BEFORE_ACTION. */
                *yy_cp = yyg->yy_hold_char;
                YY_RESTORE_YY_MORE_OFFSET
                if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
{
                        /* We're scanning a new file or input source.  It's
                         * possible that this happened because the user
                         * just pointed yyin at a new source and called
                         * mimosa_http_request_lex().  If so, then we have to assure
                         * consistency between YY_CURRENT_BUFFER and our
                         * globals.  Here is the right place to do so, because
                         * this is the first action (other than possibly a
                         * back-up) that will match for the new input source.
                         */
                        yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
                        YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
                        YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
                        }
                /* Note that here we test for yy_c_buf_p "<=" to the position
                 * of the first EOB in the buffer, since yy_c_buf_p will
                 * already have been incremented past the NUL character
                 * (since all states make transitions on EOB to the
                 * end-of-buffer state).  Contrast this with the test
                 * in input().
                 */
                if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
                        { /* This was really a NUL. */
                        yy_state_type yy_next_state;
                        yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;
                        yy_current_state = yy_get_previous_state( yyscanner );
                        /* Okay, we're now positioned to make the NUL
                         * transition.  We couldn't have
                         * yy_get_previous_state() go ahead and do it
                         * for us because it doesn't know how to deal
                         * with the possibility of jamming (and we don't
                         * want to build jamming into it because then it
                         * will run more slowly).
                         */
                        yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);
                        yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
                        if ( yy_next_state )
{
                                /* Consume the NUL. */
                                yy_cp = ++yyg->yy_c_buf_p;
                                yy_current_state = yy_next_state;
                                goto yy_match;
                                }
                        else
{
                                yy_cp = yyg->yy_c_buf_p;
                                goto yy_find_action;
                                }
                        }
                else switch ( yy_get_next_buffer( yyscanner ) )
{
                        case EOB_ACT_END_OF_FILE:
{
                                yyg->yy_did_buffer_switch_on_eof = 0;
                                if ( mimosa_http_request_wrap(yyscanner ) )
{
                                        /* Note: because we've taken care in
                                         * yy_get_next_buffer() to have set up
                                         * yytext, we can now set up
                                         * yy_c_buf_p so that if some total
                                         * hoser (like flex itself) wants to
                                         * call the scanner after we return the
                                         * YY_NULL, it'll still work - another
                                         * YY_NULL will get returned.
                                         */
                                        yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;
                                        yy_act = YY_STATE_EOF(YY_START);
                                        goto do_action;
                                        }
                                else
{
                                        if ( ! yyg->yy_did_buffer_switch_on_eof )
                                                YY_NEW_FILE;
                                        }
                                break;
                                }
                        case EOB_ACT_CONTINUE_SCAN:
                                yyg->yy_c_buf_p =
                                        yyg->yytext_ptr + yy_amount_of_matched_text;
                                yy_current_state = yy_get_previous_state( yyscanner );
                                yy_cp = yyg->yy_c_buf_p;
                                yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
                                goto yy_match;
                        case EOB_ACT_LAST_MATCH:
                                yyg->yy_c_buf_p =
                                &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];
                                yy_current_state = yy_get_previous_state( yyscanner );
                                yy_cp = yyg->yy_c_buf_p;
                                yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
                                goto yy_find_action;
                        }
                break;
                }
        default:
                YY_FATAL_ERROR(
                        "fatal flex scanner internal error--no action found" );
        } /* end of action switch */
                } /* end of scanning one token */
} /* end of mimosa_http_request_lex */
int mimosa_http_request_lex_destroy (yyscan_t yyscanner)
Definition at line 6872 of file request-lexer.cc.
References mimosa_http_request__delete_buffer(), mimosa_http_request_free(), mimosa_http_request_pop_buffer_state(), yyguts_t::yy_buffer_stack, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_init_globals(), and yyguts_t::yy_start_stack.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Pop the buffer stack, destroying each element. */
        while(YY_CURRENT_BUFFER){
                mimosa_http_request__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
                YY_CURRENT_BUFFER_LVALUE = NULL;
                mimosa_http_request_pop_buffer_state(yyscanner);
        }
        /* Destroy the stack itself. */
        mimosa_http_request_free(yyg->yy_buffer_stack ,yyscanner);
        yyg->yy_buffer_stack = NULL;
    /* Destroy the start condition stack. */
        mimosa_http_request_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;
    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * mimosa_http_request_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);
    /* Destroy the main struct (reentrant only). */
    mimosa_http_request_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}
int mimosa_http_request_lex_init (yyscan_t * scanner)
Definition at line 6781 of file request-lexer.cc.
References mimosa_http_request_alloc(), and yy_init_globals().
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
    *ptr_yy_globals = (yyscan_t) mimosa_http_request_alloc ( sizeof( struct yyguts_t ), NULL );
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    return yy_init_globals ( *ptr_yy_globals );
}
int mimosa_http_request_lex_init_extra (std::string * user_defined, yyscan_t * scanner)
Definition at line 6810 of file request-lexer.cc.
References mimosa_http_request_alloc(), mimosa_http_request_set_extra(), and yy_init_globals().
{
    struct yyguts_t dummy_yyguts;
    mimosa_http_request_set_extra (yy_user_defined, &dummy_yyguts);
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
    *ptr_yy_globals = (yyscan_t) mimosa_http_request_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    mimosa_http_request_set_extra (yy_user_defined, *ptr_yy_globals);
    return yy_init_globals ( *ptr_yy_globals );
}
void mimosa_http_request_pop_buffer_state (yyscan_t yyscanner)
Removes and deletes the top of the stack, if present. The next element becomes the new top.
Parameters:
yyscanner The scanner object.
Definition at line 6399 of file request-lexer.cc.
References mimosa_http_request__delete_buffer(), mimosa_http_request__load_buffer_state(), yyguts_t::yy_buffer_stack_top, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yyguts_t::yy_did_buffer_switch_on_eof.
Referenced by mimosa_http_request_lex_destroy().
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        if (!YY_CURRENT_BUFFER)
                return;
        mimosa_http_request__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
        YY_CURRENT_BUFFER_LVALUE = NULL;
        if (yyg->yy_buffer_stack_top > 0)
                --yyg->yy_buffer_stack_top;
        if (YY_CURRENT_BUFFER) {
                mimosa_http_request__load_buffer_state(yyscanner );
                yyg->yy_did_buffer_switch_on_eof = 1;
        }
}
void mimosa_http_request_push_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack. The new state becomes the current state. This function will allocate the stack if necessary.
Parameters:
new_buffer The new state.
yyscanner The scanner object.
Definition at line 6368 of file request-lexer.cc.
References mimosa_http_request__load_buffer_state(), mimosa_http_request_ensure_buffer_stack(), yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, and yyguts_t::yy_n_chars.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        if (new_buffer == NULL)
                return;
        mimosa_http_request_ensure_buffer_stack(yyscanner);
        /* This block is copied from mimosa_http_request__switch_to_buffer. */
        if ( YY_CURRENT_BUFFER )
                {
                /* Flush out information for old buffer. */
                *yyg->yy_c_buf_p = yyg->yy_hold_char;
                YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
                YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
                }
        /* Only push if top exists. Otherwise, replace top. */
        if (YY_CURRENT_BUFFER)
                yyg->yy_buffer_stack_top++;
        YY_CURRENT_BUFFER_LVALUE = new_buffer;
        /* copied from mimosa_http_request__switch_to_buffer. */
        mimosa_http_request__load_buffer_state(yyscanner );
        yyg->yy_did_buffer_switch_on_eof = 1;
}
void * mimosa_http_request_realloc (void * ptr, yy_size_t size, yyscan_t yyscanner)
Definition at line 6930 of file request-lexer.cc.
Referenced by mimosa_http_request_ensure_buffer_stack(), yy_get_next_buffer(), and yy_push_state().
{
        /* The cast to (char *) in the following accommodates both
         * implementations that use char* generic pointers, and those
         * that use void* generic pointers.  It works with the latter
         * because both ANSI C and C++ allow castless assignment from
         * any pointer type to void*, and deal with argument conversions
         * as though doing an assignment.
         */
        return (void *) realloc( (char *) ptr, size );
}
void mimosa_http_request_restart (FILE * input_file, yyscan_t yyscanner)
Immediately switch to a different input stream.
Parameters:
input_file A readable stream.
yyscanner The scanner object.
Note:
This function does not reset the start condition to INITIAL .
Definition at line 6192 of file request-lexer.cc.
References mimosa_http_request__create_buffer(), mimosa_http_request__init_buffer(), mimosa_http_request__load_buffer_state(), mimosa_http_request_ensure_buffer_stack(), YY_BUF_SIZE, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yyin.
Referenced by input(), and yy_get_next_buffer().
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        if ( ! YY_CURRENT_BUFFER ){
        mimosa_http_request_ensure_buffer_stack (yyscanner);
                YY_CURRENT_BUFFER_LVALUE =
            mimosa_http_request__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
        }
        mimosa_http_request__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
        mimosa_http_request__load_buffer_state(yyscanner );
}
void mimosa_http_request_set_column (int column_no, yyscan_t yyscanner)
Set the current column.
Parameters:
line_number
yyscanner The scanner object.
Definition at line 6719 of file request-lexer.cc.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yycolumn.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "mimosa_http_request_set_column called with no buffer" , yyscanner);
    yycolumn = column_no;
}
void mimosa_http_request_set_debug (int debug_flag, yyscan_t yyscanner)
Definition at line 6754 of file request-lexer.cc.
References yy_flex_debug.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}
void mimosa_http_request_set_extra (std::string * user_defined, yyscan_t yyscanner)
Set the user-defined data. This data is never touched by the scanner.
Parameters:
user_defined The data to be associated with this scanner.
yyscanner The scanner object.
Definition at line 6694 of file request-lexer.cc.
References yyextra.
Referenced by mimosa_http_request_lex_init_extra().
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}
void mimosa_http_request_set_in (FILE * in_str, yyscan_t yyscanner)
Set the input stream. This does not discard the current input buffer.
Parameters:
in_str A readable stream.
yyscanner The scanner object.
See also:
mimosa_http_request__switch_to_buffer
Definition at line 6736 of file request-lexer.cc.
References yyin.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}
void mimosa_http_request_set_lineno (int line_number, yyscan_t yyscanner)
Set the current line number.
Parameters:
line_number
yyscanner The scanner object.
Definition at line 6704 of file request-lexer.cc.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yylineno.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "mimosa_http_request_set_lineno called with no buffer" , yyscanner);
    yylineno = line_number;
}
void mimosa_http_request_set_lval (YYSTYPE * yylval_param, yyscan_t yyscanner)
Definition at line 6768 of file request-lexer.cc.
References yylval.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}
void mimosa_http_request_set_out (FILE * out_str, yyscan_t yyscanner)
Definition at line 6742 of file request-lexer.cc.
References yyout.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}
static void yy_fatal_error (char msg[], yyscan_t yyscanner) [static]
Referenced by mimosa_http_request_set_column(), and mimosa_http_request_set_lineno().
static void yy_fatal_error (char * msg, yyscan_t yyscanner) [static]
Definition at line 6593 of file request-lexer.cc.
References YY_EXIT_FAILURE.
{
        (void) fprintf( stderr, "%s\n", msg );
        exit( YY_EXIT_FAILURE );
}
static int yy_get_next_buffer (yyscan_t yyscanner) [static]
Definition at line 5888 of file request-lexer.cc.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, mimosa_http_request_realloc(), mimosa_http_request_restart(), yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, yyguts_t::yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, YY_INPUT, yy_buffer_state::yy_is_our_buffer, YY_MORE_ADJ, yyguts_t::yy_n_chars, YY_READ_BUF_SIZE, yyin, and yyscanner.
Referenced by input(), and mimosa_http_request_lex().
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
        register char *source = yyg->yytext_ptr;
        register int number_to_move, i;
        int ret_val;
        if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
                YY_FATAL_ERROR(
                "fatal flex scanner internal error--end of buffer missed" );
        if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
                { /* Don't try to fill the buffer, so this is an EOF. */
                if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
{
                        /* We matched a single character, the EOB, so
                         * treat this as a final EOF.
                         */
                        return EOB_ACT_END_OF_FILE;
                        }
                else
{
                        /* We matched some text prior to the EOB, first
                         * process it.
                         */
                        return EOB_ACT_LAST_MATCH;
                        }
                }
        /* Try to read more data. */
        /* First move last chars to start of buffer. */
        number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;
        for ( i = 0; i < number_to_move; ++i )
                *(dest++) = *(source++);
        if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
                /* don't do the read, it's not guaranteed to return an EOF,
                 * just force an EOF
                 */
                YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;
        else
                {
                        int num_to_read =
                        YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;
                while ( num_to_read <= 0 )
                        { /* Not enough room in the buffer - grow it. */
                        /* just a shorter name for the current buffer */
                        YY_BUFFER_STATE b = YY_CURRENT_BUFFER;
                        int yy_c_buf_p_offset =
                                (int) (yyg->yy_c_buf_p - b->yy_ch_buf);
                        if ( b->yy_is_our_buffer )
{
                                int new_size = b->yy_buf_size * 2;
                                if ( new_size <= 0 )
                                        b->yy_buf_size += b->yy_buf_size / 8;
                                else
                                        b->yy_buf_size *= 2;
                                b->yy_ch_buf = (char *)
                                        /* Include room in for 2 EOB chars. */
                                        mimosa_http_request_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
                                }
                        else
                                /* Can't grow it, we don't own it. */
                                b->yy_ch_buf = 0;
                        if ( ! b->yy_ch_buf )
                                YY_FATAL_ERROR(
                                "fatal error - scanner input buffer overflow" );
                        yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];
                        num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
                                                number_to_move - 1;
                        }
                if ( num_to_read > YY_READ_BUF_SIZE )
                        num_to_read = YY_READ_BUF_SIZE;
                /* Read in more data. */
                YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
                        yyg->yy_n_chars, (size_t) num_to_read );
                YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
                }
        if ( yyg->yy_n_chars == 0 )
                {
                if ( number_to_move == YY_MORE_ADJ )
{
                        ret_val = EOB_ACT_END_OF_FILE;
                        mimosa_http_request_restart(yyin  ,yyscanner);
                        }
                else
{
                        ret_val = EOB_ACT_LAST_MATCH;
                        YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
                                YY_BUFFER_EOF_PENDING;
                        }
                }
        else
                ret_val = EOB_ACT_CONTINUE_SCAN;
        if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
                /* Extend the array by 50%, plus the number we really need. */
                yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
                YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) mimosa_http_request_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
                if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
                        YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
        }
        yyg->yy_n_chars += number_to_move;
        YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
        YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;
        yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];
        return ret_val;
}
static yy_state_type yy_get_previous_state (yyscan_t yyscanner) [static]
Definition at line 6023 of file request-lexer.cc.
References yyguts_t::yy_c_buf_p, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, YY_MORE_ADJ, YY_SC_TO_UI, and yyguts_t::yy_start.
Referenced by mimosa_http_request_lex().
{
        register yy_state_type yy_current_state;
        register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        yy_current_state = yy_start_state_list[yyg->yy_start];
        for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
                {
                yy_current_state += yy_current_state[(*yy_cp ? YY_SC_TO_UI(*yy_cp) : 256)].yy_nxt;
                if ( yy_current_state[-1].yy_nxt )
{
                        yyg->yy_last_accepting_state = yy_current_state;
                        yyg->yy_last_accepting_cpos = yy_cp;
                        }
                }
        return yy_current_state;
}
static int yy_init_globals (yyscan_t yyscanner) [static]
Definition at line 6838 of file request-lexer.cc.
References yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, yyguts_t::yy_init, yyguts_t::yy_start, yyguts_t::yy_start_stack, yyguts_t::yy_start_stack_depth, yyguts_t::yy_start_stack_ptr, yyin, and yyout.
Referenced by mimosa_http_request_lex_destroy(), mimosa_http_request_lex_init(), and mimosa_http_request_lex_init_extra().
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from mimosa_http_request_lex_destroy(), so don't allocate here.
     */
    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;
    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;
/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif
    /* For future reference: Set errno on error, since we are called by
     * mimosa_http_request_lex_init()
     */
    return 0;
}
static void yy_pop_state (yyscan_t yyscanner) [static]
Definition at line 6574 of file request-lexer.cc.
References BEGIN, YY_FATAL_ERROR, yyguts_t::yy_start_stack, and yyguts_t::yy_start_stack_ptr.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        if ( --yyg->yy_start_stack_ptr < 0 )
                YY_FATAL_ERROR( "start-condition stack underflow" );
        BEGIN(yyg->yy_start_stack[yyg->yy_start_stack_ptr]);
}
static void yy_push_state (int new_state, yyscan_t yyscanner) [static]
Definition at line 6549 of file request-lexer.cc.
References BEGIN, mimosa_http_request_alloc(), mimosa_http_request_realloc(), YY_FATAL_ERROR, YY_START, yyguts_t::yy_start_stack, yyguts_t::yy_start_stack_depth, YY_START_STACK_INCR, yyguts_t::yy_start_stack_ptr, and yyscanner.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        if ( yyg->yy_start_stack_ptr >= yyg->yy_start_stack_depth )
                {
                yy_size_t new_size;
                yyg->yy_start_stack_depth += YY_START_STACK_INCR;
                new_size = yyg->yy_start_stack_depth * sizeof( int );
                if ( ! yyg->yy_start_stack )
                        yyg->yy_start_stack = (int *) mimosa_http_request_alloc(new_size ,yyscanner );
                else
                        yyg->yy_start_stack = (int *) mimosa_http_request_realloc((void *) yyg->yy_start_stack,new_size ,yyscanner );
                if ( ! yyg->yy_start_stack )
                        YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
                }
        yyg->yy_start_stack[yyg->yy_start_stack_ptr++] = YY_START;
        BEGIN(new_state);
}
static int yy_top_state (yyscan_t yyscanner) [static]
Definition at line 6583 of file request-lexer.cc.
References yyguts_t::yy_start_stack, and yyguts_t::yy_start_stack_ptr.
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
        return yyg->yy_start_stack[yyg->yy_start_stack_ptr - 1];
}
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner) [static]
Definition at line 6049 of file request-lexer.cc.
References yyguts_t::yy_c_buf_p, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, yy_trans_info::yy_nxt, yy_trans_info::yy_verify, and yyconst.
Referenced by mimosa_http_request_lex().
{
        register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
        register char *yy_cp = yyg->yy_c_buf_p;
        register int yy_c = 256;
        register yyconst struct yy_trans_info *yy_trans_info;
        yy_trans_info = &yy_current_state[(unsigned int) yy_c];
        yy_current_state += yy_trans_info->yy_nxt;
        yy_is_jam = (yy_trans_info->yy_verify != yy_c);
        if ( ! yy_is_jam )
                {
                if ( yy_current_state[-1].yy_nxt )
{
                        yyg->yy_last_accepting_state = yy_current_state;
                        yyg->yy_last_accepting_cpos = yy_cp;
                        }
                }
        return yy_is_jam ? 0 : yy_current_state;
}
static void yyunput (int c, char * buf_ptr, yyscan_t yyscanner) [static]
static void yyunput (int c, register char * yy_bp, yyscan_t yyscanner) [static]
Definition at line 6074 of file request-lexer.cc.
References yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, YY_FATAL_ERROR, yyguts_t::yy_hold_char, and yyguts_t::yy_n_chars.
{
        register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_cp = yyg->yy_c_buf_p;
        /* undo effects of setting up yytext */
        *yy_cp = yyg->yy_hold_char;
        if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
                { /* need to shift things up to make room */
                /* +2 for EOB chars. */
                register int number_to_move = yyg->yy_n_chars + 2;
                register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
                                        YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
                register char *source =
                                &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];
                while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
                        *--dest = *--source;
                yy_cp += (int) (dest - source);
                yy_bp += (int) (dest - source);
                YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
                        yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;
                if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
                        YY_FATAL_ERROR( "flex scanner push-back overflow" );
                }
        *--yy_cp = (char) c;
        yyg->yytext_ptr = yy_bp;
        yyg->yy_hold_char = *yy_cp;
        yyg->yy_c_buf_p = yy_cp;
}
Variable Documentation
struct yy_trans_info* yy_start_state_list[35] [static]
Definition at line 5099 of file request-lexer.cc.
struct yy_trans_info yy_transition[21785] [static]
Definition at line 359 of file request-lexer.cc.