mimosa: mimosa/http/samples/web-server.cc File Reference
web-server.cc File Reference
#include <sstream>
#include <gflags/gflags.h>
#include <mimosa/main.hh>
#include <mimosa/http/server.hh>
#include <mimosa/http/dispatch-handler.hh>
#include <mimosa/http/fs-handler.hh>
Data Structures
class HelloHandler
class QueryEchoHandler
class PostEchoHandler
struct __mimosa_main_data
Functions
DEFINE_int32 (port, 4242,"the port to use")
DEFINE_string (path,"/usr/include","the data dir to expose")
DEFINE_string (cert,"","the certificate (cert.pem)")
DEFINE_string (key,"","the key (key.pem)")
int __mimosa_main (int argc, char **argv)
void * __mimosa_main_wrapper (__mimosa_main_data *data)
int main (int argc, char **argv)
Function Documentation
int __mimosa_main (int argc, char ** argv)
Definition at line 98 of file web-server.cc.
{
  (void)argc;
  (void)argv;
  auto dispatch(new http::DispatchHandler);
  dispatch->registerHandler("/", new HelloHandler);
  dispatch->registerHandler("/query-echo", new QueryEchoHandler);
  dispatch->registerHandler("/post-echo", new PostEchoHandler);
  dispatch->registerHandler("/data/*", new http::FsHandler(FLAGS_path, 1, true));
  http::Server::Ptr server = new http::Server;
  server->setHandler(dispatch);
  if (!FLAGS_cert.empty() && !FLAGS_key.empty())
    server->setSecure(FLAGS_cert, FLAGS_key);
  auto ret = server->listenInet4(FLAGS_port);
  if (!ret)
  {
    puts("failed to listen");
    return 1;
  }
  printf("listen on %d succeed\n", FLAGS_port);
  mimosa::runtime::sleep(mimosa::runtime::minutes(15));
  server->stop();
  return 0;
}
void* __mimosa_main_wrapper (__mimosa_main_data * data)
Definition at line 98 of file web-server.cc.
{
DEFINE_int32 (port , 4242 , "the port to use")
DEFINE_string (path , "/usr/include" , "the data dir to expose")
DEFINE_string (cert , "" , "the certificate (cert.pem)")
DEFINE_string (key , "" , "the key (key.pem)")
int main (int argc, char ** argv)
Definition at line 98 of file web-server.cc.
References mimosa::runtime::minutes(), mimosa::http::Server::setHandler(), and mimosa::runtime::sleep().
{